/* obj1data.c — the obj1-arena overlay loader (hand-written; the obj1 twin of obj3_build.c).
 *
 * Workstream-B: turns the zero-filled obj1 arena into the boot-ready DATA arena by overlaying
 * the NAMED/TYPED OWNED obj1-resident cells (obj1_owned.{c,h}, GENERATED by
 * tools/gen_obj1_symbols.py from recomp/datac/obj1_owned.json) at their canon offsets. Each owned
 * C object is the ONLY source of its bytes (drop this loop and obj1-probe goes red structurally).
 *
 * There is NO template copy and NO reloc pass here (unlike obj3_build.c): obj1 is the CODE object,
 * the arena is zero-filled by imgfree_boot's mmap, and every owned region is fixup-free (asserted
 * by gen_obj1_symbols.py). The 4 fixup-carrying code-ptr tables stay token-staged by imgfree_boot
 * until the model flip — they are NOT in obj1_owned_tab.
 */
#include "obj1data.h"
#include "obj1_owned.h"

void obj1data_build(unsigned char *arena)
{
    for (unsigned i = 0; i < obj1_owned_count; i++) {
        const obj1_owned_t *o = &obj1_owned_tab[i];
        const unsigned char *src = (const unsigned char *)o->ptr;
        unsigned char *dst = arena + o->off;      /* off = canon - 0x10000 */
        for (unsigned j = 0; j < o->size; j++)
            dst[j] = src[j];
    }
}
