/* obj1data.h — the obj1-arena overlay loader (hand-written; the obj1 twin of obj3_build.c).
 *
 * Workstream-B: the image-free boot (src/platform/imgfree_boot.c) maps the obj1 canon range
 * as a zero-filled RW arena (NO original CODE bytes) and calls obj1data_build() to overlay the
 * obj1-resident DATA cells the game reads. Those cells are the NAMED/TYPED OWNED C definitions in
 * obj1_owned.{c,h} (GENERATED by tools/gen_obj1_symbols.py from recomp/datac/obj1_owned.json);
 * obj1data_build copies each owned symbol's storage to its canon offset in the arena. The lifted
 * TUs keep reading the arena through their existing G8/G16/G32(0xADDR) sites.
 *
 * (This header used to declare the anonymous {canon,len,bytes[]} byte-range table generated by
 * gen_obj1data_c.py; replaced that with the named/typed owned symbols — obj1data_build now
 * overlays obj1_owned_tab. The obj1data_build(arena) contract is unchanged.)
 */
#ifndef ROTH_OBJ1DATA_H
#define ROTH_OBJ1DATA_H

/* Stage the OWNED obj1-resident DATA cells into the zero-filled obj1 arena.
 * arena = the runtime address of canon 0x10000 (OBJ1_BASE); dst = arena + (canon - 0x10000). */
void obj1data_build(unsigned char *arena);

#endif /* ROTH_OBJ1DATA_H */
