/* GENERATED by tools/gen_obj3_symbols.py — do not edit by hand. */
#include "obj3_symbols.h"
#include <stdio.h>
#include <string.h>

const obj3_sym_t obj3_symtab[] = {
  { "g_crt_data_seg_prefix", 0x70000u, 0x0u, 0x10u, 0x10u, 2, 8, 0, 1 },
  { "g_default_response_file_msg", 0x70010u, 0x10u, 0x17u, 0x17u, 2, 8, 0, 1 },
  { "g_startup_banner", 0x70027u, 0x27u, 0x81u, 0x81u, 2, 8, 0, 1 },
  { "g_startup_device_msgs", 0x700a8u, 0xa8u, 0x64u, 0x64u, 2, 8, 0, 1 },
  { "g_msg_initiating_das", 0x7010cu, 0x10cu, 0x16u, 0x16u, 2, 8, 0, 1 },
  { "g_msg_direct_screen", 0x70122u, 0x122u, 0x1fu, 0x1fu, 2, 8, 0, 1 },
  { "g_msg_overscan_screen", 0x70141u, 0x141u, 0x21u, 0x21u, 2, 8, 0, 1 },
  { "g_msg_detecting_vesa", 0x70162u, 0x162u, 0x19u, 0x19u, 2, 8, 0, 1 },
  { "g_msg_hires_screen", 0x7017bu, 0x17bu, 0x1eu, 0x1eu, 2, 8, 0, 1 },
  { "g_msg_blur_selected", 0x70199u, 0x199u, 0x16u, 0x16u, 2, 8, 0, 1 },
  { "g_msg_starting_midi", 0x701afu, 0x1afu, 0x18u, 0x18u, 2, 8, 0, 1 },
  { "g_msg_installing_sound", 0x701c7u, 0x1c7u, 0x1fu, 0x1fu, 2, 8, 0, 1 },
  { "g_msg_ok", 0x701e6u, 0x1e6u, 0x6u, 0x6u, 2, 8, 0, 1 },
  { "g_cfg_file_arg", 0x701ecu, 0x1ecu, 0x50u, 0x50u, 2, 8, 0, 1 },
  { "g_cfg_das_arg", 0x7023cu, 0x23cu, 0x50u, 0x50u, 2, 8, 0, 1 },
  { "g_cfg_snd_arg", 0x7028cu, 0x28cu, 0x50u, 0x50u, 2, 8, 0, 1 },
  { "g_cfg_das2_arg", 0x702dcu, 0x2dcu, 0x1c9u, 0x1c9u, 2, 8, 0, 1 },
  { "g_arg_command_table", 0x704a5u, 0x4a5u, 0x293u, 0x293u, 2, 8, 0, 1 },
  { "g_snapshot_basename", 0x70738u, 0x738u, 0xcu, 0xcu, 2, 8, 0, 1 },
  { "g_snapshot_name_seq", 0x70744u, 0x744u, 0x2u, 0x2u, 0, 16, 0, 1 },
  { "g_snapshot_anim_frame", 0x70746u, 0x746u, 0x6du, 0x6du, 2, 8, 0, 1 },
  { "g_mouse_x", 0x707b3u, 0x7b3u, 0x4u, 0x4u, 0, 32, 0, 1 },
  { "g_mouse_y", 0x707b7u, 0x7b7u, 0x4u, 0x4u, 0, 32, 0, 1 },
  { "g_pixel_extent_scale", 0x707bbu, 0x7bbu, 0x2u, 0x2u, 0, 16, 0, 1 },
  { "g_dbg_tilt_fmt", 0x707bdu, 0x7bdu, 0xcu, 0xcu, 2, 8, 0, 1 },
  { "g_kbd_dir_offset_table", 0x707c9u, 0x7c9u, 0x2u, 0x4u, 0, 16, 0, 1 },
  { "g_kbd_dir_offset_table_ext", 0x707cdu, 0x7cdu, 0x1cu, 0x1cu, 2, 8, 0, 1 },
  { "g_keybit_mask_table", 0x707e9u, 0x7e9u, 0x1u, 0x1u, 0, 8, 0, 1 },
  { "g_keybit_mask_table_ext", 0x707eau, 0x7eau, 0x7u, 0x7u, 2, 8, 0, 1 },
  { "g_held_key_move_table", 0x707f1u, 0x7f1u, 0x3du, 0x3du, 2, 8, 0, 1 },
  { "g_scancode_translate_table", 0x7082eu, 0x82eu, 0xb6u, 0xb6u, 2, 8, 0, 1 },
  { "g_current_cursor_id", 0x708e4u, 0x8e4u, 0x2u, 0x2u, 0, 16, 0, 1 },
  { "g_cursor_mask_data", 0x708e6u, 0x8e6u, 0x57u, 0x57u, 2, 8, 0, 1 },
  { "g_keymap_table", 0x7093du, 0x93du, 0x5d5u, 0x5d5u, 2, 8, 0, 1 },
  { "g_font_descriptor", 0x70f12u, 0xf12u, 0x2f6u, 0x2f6u, 2, 8, 0, 1 },
  { "g_ui_slot_layout_table", 0x71208u, 0x1208u, 0x2u, 0x2u, 0, 16, 0, 1 },
  { "g_ui_slot_layout_table_ext", 0x7120au, 0x120au, 0x2u, 0x2u, 0, 16, 0, 1 },
  { "g_ui_slot_layout_table_body", 0x7120cu, 0x120cu, 0x30u, 0x30u, 2, 8, 0, 1 },
  { "g_inventory_tab_context_map", 0x7123cu, 0x123cu, 0x12au, 0x12au, 2, 8, 0, 1 },
  { "g_bit_mask_lut", 0x71366u, 0x1366u, 0x1u, 0x1u, 0, 8, 0, 1 },
  { "g_bit_mask_lut_ext", 0x71367u, 0x1367u, 0x9u, 0x9u, 2, 8, 0, 1 },
  { "g_choice_selected_index", 0x71370u, 0x1370u, 0x68cu, 0x68cu, 2, 8, 0, 1 },
  { "g_mouse_speed", 0x719fcu, 0x19fcu, 0x138u, 0x138u, 2, 8, 0, 1 },
  { "g_vol_soundfx", 0x71b34u, 0x1b34u, 0xcu, 0xcu, 2, 8, 0, 1 },
  { "g_vol_speech", 0x71b40u, 0x1b40u, 0xcu, 0xcu, 2, 8, 0, 1 },
  { "g_vol_movie", 0x71b4cu, 0x1b4cu, 0xcu, 0xcu, 2, 8, 0, 1 },
  { "g_vol_music", 0x71b58u, 0x1b58u, 0x1adu, 0x1adu, 2, 8, 0, 1 },
  { "g_message_box_state", 0x71d05u, 0x1d05u, 0x41u, 0x41u, 2, 8, 0, 1 },
  { "g_gdv_error_strings", 0x71d46u, 0x1d46u, 0x4u, 0x4u, 0, 32, 0, 1 },
  { "g_test_sfx_descriptor", 0x71d4au, 0x1d4au, 0x4au, 0x4au, 2, 8, 0, 1 },
  { "g_hex_digits_lower", 0x71d94u, 0x1d94u, 0x10u, 0x10u, 2, 8, 0, 1 },
  { "g_hex_digits_upper", 0x71da4u, 0x1da4u, 0x10u, 0x10u, 2, 8, 0, 1 },
  { "g_shade_const_table_a", 0x71db4u, 0x1db4u, 0x2u, 0x2u, 0, 16, 0, 1 },
  { "g_shade_const_table_a_ext", 0x71db6u, 0x1db6u, 0x4u, 0x4u, 2, 8, 0, 1 },
  { "g_shade_const_table_b", 0x71dbau, 0x1dbau, 0x2u, 0x2u, 0, 16, 0, 1 },
  { "g_shade_const_table_b_ext", 0x71dbcu, 0x1dbcu, 0x8u, 0x8u, 2, 8, 0, 1 },
  { "g_vesa_page_bank_offset", 0x71dc4u, 0x1dc4u, 0x2u, 0x2u, 2, 8, 0, 1 },
  { "g_current_vesa_bank", 0x71dc6u, 0x1dc6u, 0x6u, 0x6u, 1, 16, 0, 1 },
  { "g_vesa_available", 0x71dccu, 0x1dccu, 0x1u, 0x4u, 0, 8, 0, 1 },
  { "g_init_stage_error_strings", 0x71dd0u, 0x1dd0u, 0x160u, 0x160u, 2, 8, 0, 1 },
  { "g_anim_step_fn_table", 0x71f30u, 0x1f30u, 0x18u, 0x18u, 2, 8, 0, 1 },
  { "g_command_rng", 0x71f48u, 0x1f48u, 0x4u, 0x4u, 0, 32, 0, 1 },
  { "g_msg_pool_damaged", 0x71f4cu, 0x1f4cu, 0x34u, 0x34u, 2, 8, 0, 1 },
  { "g_world_span_variant_table", 0x71f80u, 0x1f80u, 0x100u, 0x100u, 1, 32, 0, 1 },
  { "g_sincos_table", 0x72080u, 0x2080u, 0x400u, 0x400u, 1, 16, 0, 1 },
  { "g_snapshot_counter", 0x72480u, 0x2480u, 0x2u, 0x2u, 0, 16, 0, 1 },
  { "g_snapshot_filenames", 0x72482u, 0x2482u, 0x46u, 0x46u, 2, 8, 0, 1 },
  { "g_door_vertex_template", 0x724c8u, 0x24c8u, 0x2u, 0x2u, 0, 16, 0, 1 },
  { "g_door_vertex_template_body", 0x724cau, 0x24cau, 0x26u, 0x26u, 2, 8, 0, 1 },
  { "g_player_walk_bob_table", 0x724f0u, 0x24f0u, 0x2u, 0x2u, 0, 16, 0, 1 },
  { "g_player_walk_bob_table_body", 0x724f2u, 0x24f2u, 0x42u, 0x42u, 2, 8, 0, 1 },
  { "g_heap_brk", 0x72534u, 0x2534u, 0x4u, 0x4u, 2, 8, 0, 1 },
  { "g_response_file_arg", 0x72538u, 0x2538u, 0x4u, 0xcu, 0, 32, 0, 1 },
  { "g_stack_limit", 0x72544u, 0x2544u, 0x18u, 0x18u, 2, 8, 0, 1 },
  { "g_dos_child_running", 0x7255cu, 0x255cu, 0x6u, 0x6u, 2, 8, 0, 1 },
  { "g_crt_memory_mode", 0x72562u, 0x2562u, 0x1cau, 0x1cau, 2, 8, 0, 1 },
  { "g_entity_damage_rng", 0x7272cu, 0x272cu, 0x4u, 0x4u, 2, 8, 0, 1 },
  { "g_ai_wander_rng", 0x72730u, 0x2730u, 0x4u, 0x4u, 2, 8, 0, 1 },
  { "g_ai_anim_rng", 0x72734u, 0x2734u, 0x4u, 0x4u, 0, 32, 0, 1 },
  { "g_ai_anim_rng_seed", 0x72738u, 0x2738u, 0x4u, 0x4u, 2, 8, 0, 1 },
  { "g_actor_anim_scheduler", 0x7273cu, 0x273cu, 0x4u, 0x4u, 0, 32, 0, 1 },
  { "g_actor_move_rate", 0x72740u, 0x2740u, 0x1u, 0x4u, 0, 8, 0, 1 },
  { "g_actor_tick_rate", 0x72744u, 0x2744u, 0x4u, 0x8u, 0, 32, 0, 1 },
  { "g_actor_tick_rate_ext", 0x7274cu, 0x274cu, 0x20u, 0x20u, 2, 8, 0, 1 },
  { "g_rng_state", 0x7276cu, 0x276cu, 0x2u, 0x6u, 0, 16, 0, 1 },
  { "g_screen_mode_table", 0x72772u, 0x2772u, 0x17eu, 0x17eu, 2, 8, 0, 1 },
  { "g_index_class_table", 0x728f0u, 0x28f0u, 0x18u, 0x18u, 2, 8, 0, 1 },
  { "g_sos_sequence_ctx_table", 0x72908u, 0x2908u, 0xd0u, 0xd0u, 2, 8, 0, 1 },
  { "g_midi_logical_to_physical_chan", 0x729d8u, 0x29d8u, 0x2d0u, 0x2d0u, 2, 8, 0, 1 },
  { "g_midi_physical_to_logical_chan", 0x72ca8u, 0x2ca8u, 0x50u, 0x50u, 2, 8, 0, 1 },
  { "g_midi_physical_chan_device", 0x72cf8u, 0x2cf8u, 0x50u, 0x50u, 2, 8, 0, 1 },
  { "g_midi_channel_saved_state", 0x72d48u, 0x2d48u, 0x640u, 0x640u, 2, 8, 0, 1 },
  { "g_midi_channel_patch", 0x73388u, 0x3388u, 0x330u, 0x330u, 2, 8, 0, 1 },
  { "g_midi_physical_chan_busy", 0x736b8u, 0x36b8u, 0x50u, 0x50u, 2, 8, 0, 1 },
  { "g_sound_master_volume", 0x73708u, 0x3708u, 0x1u, 0x4u, 0, 8, 0, 1 },
  { "g_sound_channel_volume", 0x7370cu, 0x370cu, 0x20u, 0x20u, 2, 8, 0, 1 },
  { "g_midi_channel_raw_volume", 0x7372cu, 0x372cu, 0xaccu, 0xaccu, 2, 8, 0, 1 },
  { "g_sos_timer_base_rate", 0x741f8u, 0x41f8u, 0x4u, 0x4u, 2, 8, 0, 1 },
  { "g_sos_timer_event_countdown", 0x741fcu, 0x41fcu, 0x13d0u, 0x13d0u, 2, 8, 0, 1 },
  { "environ", 0x755ccu, 0x55ccu, 0x44u, 0x44u, 2, 8, 0, 1 },
  { "g_heap_free_list", 0x75610u, 0x5610u, 0xda0u, 0xda0u, 2, 8, 0, 1 },
  { "g_dir_data", 0x763b0u, 0x63b0u, 0x50u, 0x50u, 2, 8, 1, 1 },
  { "g_dir_midi", 0x76400u, 0x6400u, 0x50u, 0x50u, 2, 8, 1, 1 },
  { "g_dir_digi", 0x76450u, 0x6450u, 0xa0u, 0xa0u, 2, 8, 1, 1 },
  { "g_dir_gdv", 0x764f0u, 0x64f0u, 0x144u, 0x144u, 1, 8, 1, 1 },
  { "g_video_linear_flag", 0x76634u, 0x6634u, 0xdcu, 0xdcu, 2, 8, 1, 1 },
  { "g_map_list_ptr", 0x76710u, 0x6710u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_arg_token_buf", 0x76718u, 0x6718u, 0x32u, 0x32u, 1, 8, 1, 1 },
  { "g_player_movement_enabled", 0x7674au, 0x674au, 0x13u, 0x13u, 2, 8, 1, 1 },
  { "g_map_menu_marker_selected", 0x7675du, 0x675du, 0x1u, 0x1u, 0, 8, 1, 1 },
  { "g_default_message_color", 0x7675eu, 0x675eu, 0x1u, 0x7u, 0, 8, 1, 1 },
  { "g_map_menu_marker_normal", 0x76765u, 0x6765u, 0x1u, 0x5bu, 0, 8, 1, 1 },
  { "g_version_string", 0x767c0u, 0x67c0u, 0x80u, 0x80u, 2, 8, 1, 1 },
  { "g_snapshot_enabled", 0x76840u, 0x6840u, 0x1u, 0x4u, 0, 8, 1, 1 },
  { "g_console_input_maxlen", 0x76844u, 0x6844u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_console_input_pos", 0x76848u, 0x6848u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_console_input_buffer", 0x7684cu, 0x684cu, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_console_input_numeric_only", 0x76854u, 0x6854u, 0x1u, 0x1cu, 0, 8, 1, 1 },
  { "g_mouse_dx", 0x76870u, 0x6870u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_mouse_dy", 0x76874u, 0x6874u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_saveunder_sprite_color_ptr", 0x76878u, 0x6878u, 0x4u, 0x18u, 0, 32, 1, 1 },
  { "g_cursor_prev_x", 0x76890u, 0x6890u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_cursor_prev_y", 0x76894u, 0x6894u, 0x4u, 0x8034u, 0, 32, 1, 1 },
  { "g_screen_busy_depth", 0x7e8c8u, 0xe8c8u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_mouse_relative_mode", 0x7e8d0u, 0xe8d0u, 0x1u, 0x4u, 0, 8, 1, 1 },
  { "g_frame_tick_callback", 0x7e8d4u, 0xe8d4u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_move_speed_accum", 0x7e8d8u, 0xe8d8u, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_run_toggle", 0x7e8dcu, 0xe8dcu, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_run_active", 0x7e8e0u, 0xe8e0u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_saved_int8_offset", 0x7e8e4u, 0xe8e4u, 0x4u, 0x4u, 2, 8, 1, 0 },
  { "g_saved_int9_offset", 0x7e8e8u, 0xe8e8u, 0x4u, 0x2cu, 0, 32, 1, 1 },
  { "g_saved_int8_segment", 0x7e914u, 0xe914u, 0x2u, 0x2u, 2, 8, 1, 0 },
  { "g_saved_int9_segment", 0x7e916u, 0xe916u, 0x2u, 0xau, 0, 16, 1, 1 },
  { "g_move_input_bits", 0x7e920u, 0xe920u, 0x2u, 0x8u, 0, 16, 1, 1 },
  { "g_mouse_buttons_held", 0x7e928u, 0xe928u, 0x1u, 0x1u, 0, 8, 1, 1 },
  { "g_mouse_buttons_prev", 0x7e929u, 0xe929u, 0x1u, 0x9u, 0, 8, 1, 1 },
  { "g_interaction_cursor_type", 0x7e932u, 0xe932u, 0x1u, 0x6u, 0, 8, 1, 1 },
  { "g_cursor_primary_action_flag", 0x7e938u, 0xe938u, 0x1u, 0x1u, 0, 8, 1, 1 },
  { "g_cursor_secondary_action_flag", 0x7e939u, 0xe939u, 0x1u, 0x1u, 0, 8, 1, 1 },
  { "g_mouse_click_edges", 0x7e93au, 0xe93au, 0x1u, 0x16u, 0, 8, 1, 1 },
  { "g_cursor_sprite", 0x7e950u, 0xe950u, 0x900u, 0x900u, 2, 8, 1, 1 },
  { "g_cursor_changed", 0x7f250u, 0xf250u, 0x1u, 0x4u, 0, 8, 1, 1 },
  { "g_view_grayscale_lut", 0x7f254u, 0xf254u, 0x100u, 0x100u, 2, 8, 1, 1 },
  { "g_view_grayscale_lut_valid", 0x7f354u, 0xf354u, 0x1u, 0x1u, 0, 8, 1, 1 },
  { "g_rect_fill_color", 0x7f355u, 0xf355u, 0x1u, 0x3u, 0, 8, 1, 1 },
  { "g_screen_resolution_index", 0x7f358u, 0xf358u, 0x12u, 0x12u, 2, 8, 1, 1 },
  { "g_render_mode", 0x7f36au, 0xf36au, 0x2u, 0x4u, 0, 16, 1, 1 },
  { "g_debug_map_enabled", 0x7f36eu, 0xf36eu, 0x1u, 0x4u, 0, 8, 1, 1 },
  { "g_display_type", 0x7f372u, 0xf372u, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_game_heap_handle", 0x7f374u, 0xf374u, 0x4u, 0xd0u, 0, 32, 1, 1 },
  { "g_audio_sequence_ctx", 0x7f444u, 0xf444u, 0xcu, 0xcu, 1, 32, 1, 1 },
  { "g_dbase300_chunk_buf", 0x7f450u, 0xf450u, 0x4u, 0x18u, 0, 32, 1, 1 },
  { "g_audio_sequence_progress", 0x7f468u, 0xf468u, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_current_dbase300_chunk_id", 0x7f46cu, 0xf46cu, 0x8u, 0x8u, 1, 32, 1, 1 },
  { "g_audio_sequence_pending", 0x7f474u, 0xf474u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_audio_signed_samples", 0x7f478u, 0xf478u, 0x4u, 0x64u, 0, 32, 1, 1 },
  { "g_sos_digital_device", 0x7f4dcu, 0xf4dcu, 0x74u, 0x74u, 1, 32, 1, 1 },
  { "g_sound_enabled", 0x7f550u, 0xf550u, 0x4u, 0x10u, 0, 32, 1, 1 },
  { "g_dev_mode_flag", 0x7f560u, 0xf560u, 0x1u, 0xcu, 0, 8, 1, 1 },
  { "g_reloc_base", 0x7f56cu, 0xf56cu, 0x4u, 0x5u, 0, 32, 1, 1 },
  { "g_inventory_dirty_flags", 0x7f571u, 0xf571u, 0x1u, 0x3u, 0, 8, 1, 1 },
  { "g_cached_dbase200_sprite_handle", 0x7f574u, 0xf574u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_selected_video_mode", 0x7f578u, 0xf578u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dirty_rect_count", 0x7f57cu, 0xf57cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dirty_rects", 0x7f580u, 0xf580u, 0x400u, 0x400u, 2, 8, 1, 1 },
  { "g_prev_dirty_rect_count", 0x7f980u, 0xf980u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_prev_dirty_rects", 0x7f984u, 0xf984u, 0x400u, 0x400u, 2, 8, 1, 1 },
  { "g_item_pickup_flags", 0x7fd84u, 0xfd84u, 0x28u, 0x28u, 2, 8, 1, 1 },
  { "g_cursor_interaction_flags", 0x7fdacu, 0xfdacu, 0x10u, 0x10u, 2, 8, 1, 1 },
  { "g_corner_icon_saveunder", 0x7fdbcu, 0xfdbcu, 0x4u, 0x14u, 0, 32, 1, 1 },
  { "g_weapon_fire_lock", 0x7fdd0u, 0xfdd0u, 0x4u, 0x24u, 0, 32, 1, 1 },
  { "g_pending_weapon_def", 0x7fdf4u, 0xfdf4u, 0x4u, 0xcu, 0, 32, 1, 1 },
  { "g_active_weapon_ptr", 0x7fe00u, 0xfe00u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_rng_state2", 0x7fe08u, 0xfe08u, 0x2u, 0x4u, 0, 16, 1, 1 },
  { "g_pending_shot_scale", 0x7fe0cu, 0xfe0cu, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_pending_fire_aim", 0x7fe10u, 0xfe10u, 0x4u, 0x18u, 0, 32, 1, 1 },
  { "g_map_menu_active", 0x7fe28u, 0xfe28u, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_map_menu_count", 0x7fe2cu, 0xfe2cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_map_menu_selected_index", 0x7fe30u, 0xfe30u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_map_menu_selected_entry", 0x7fe34u, 0xfe34u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_help_overlay_enabled", 0x7fe38u, 0xfe38u, 0x70u, 0x70u, 2, 8, 1, 1 },
  { "g_pending_game_action", 0x7fea8u, 0xfea8u, 0x10u, 0x10u, 2, 8, 1, 1 },
  { "g_mouse_button_swap", 0x7feb8u, 0xfeb8u, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_inventory_options_request", 0x7febcu, 0xfebcu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_inspect_popup_active", 0x7fec0u, 0xfec0u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_inventory_panel_open", 0x7fec4u, 0xfec4u, 0x4u, 0xcu, 0, 32, 1, 1 },
  { "g_active_item_hud_icon", 0x7fed0u, 0xfed0u, 0x4u, 0x20u, 0, 32, 1, 1 },
  { "g_current_cursor_entry", 0x7fef0u, 0xfef0u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_cursor_entry_table", 0x7fef4u, 0xfef4u, 0xc00u, 0xc00u, 2, 8, 1, 1 },
  { "g_cursor_entry_count", 0x80af4u, 0x10af4u, 0x8u, 0x8u, 2, 8, 1, 1 },
  { "g_cursor_list_positions", 0x80afcu, 0x10afcu, 0x14u, 0x14u, 1, 32, 1, 1 },
  { "g_cursor_scroll_offsets", 0x80b10u, 0x10b10u, 0x14u, 0x14u, 1, 32, 1, 1 },
  { "g_ui_panel_anchor_x", 0x80b24u, 0x10b24u, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_ui_panel_anchor_y", 0x80b28u, 0x10b28u, 0x8u, 0x8u, 2, 8, 1, 1 },
  { "g_inventory_ui_action", 0x80b30u, 0x10b30u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_cursor_active_list", 0x80b38u, 0x10b38u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_inventory_inspect_request", 0x80b3cu, 0x10b3cu, 0x4u, 0x6u, 0, 32, 1, 1 },
  { "g_inspect_popup_layout", 0x80b42u, 0x10b42u, 0x2eu, 0x2eu, 1, 16, 1, 1 },
  { "g_inventory_active_tab", 0x80b70u, 0x10b70u, 0x54u, 0x54u, 2, 8, 1, 1 },
  { "g_inventory_hotspot_list", 0x80bc4u, 0x10bc4u, 0x68u, 0x68u, 2, 8, 1, 0 },
  { "g_inventory_count", 0x80c2cu, 0x10c2cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_inventory_slots", 0x80c30u, 0x10c30u, 0x400u, 0x400u, 2, 8, 1, 1 },
  { "g_left_hand_item", 0x81030u, 0x11030u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_displayed_item_left", 0x81034u, 0x11034u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_selected_item_secondary", 0x81038u, 0x11038u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_right_hand_item", 0x8103cu, 0x1103cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_displayed_item_right", 0x81040u, 0x11040u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_selected_item_primary", 0x81044u, 0x11044u, 0x4u, 0x7cu, 0, 32, 1, 1 },
  { "g_inspect_popup_state", 0x810c0u, 0x110c0u, 0x4u, 0x3cu, 0, 32, 1, 1 },
  { "g_inspect_page_count", 0x810fcu, 0x110fcu, 0x4u, 0x88u, 0, 32, 1, 1 },
  { "g_inspect_current_page", 0x81184u, 0x11184u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_inspect_info_available", 0x81188u, 0x11188u, 0x4u, 0x18u, 0, 32, 1, 1 },
  { "g_inventory_arrow_state", 0x811a0u, 0x111a0u, 0xcu, 0xcu, 2, 8, 1, 1 },
  { "g_ui_panel_scratch_handle", 0x811acu, 0x111acu, 0x8u, 0x8u, 1, 32, 1, 1 },
  { "g_active_weapon_attrs", 0x811b4u, 0x111b4u, 0x30u, 0x30u, 2, 8, 1, 1 },
  { "g_active_weapon_ammo_id", 0x811e4u, 0x111e4u, 0x118u, 0x118u, 1, 32, 1, 1 },
  { "g_inventory_synthetic_primary", 0x812fcu, 0x112fcu, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_pending_choice_accept_index", 0x81304u, 0x11304u, 0x4u, 0xcu, 0, 32, 1, 1 },
  { "g_held_item_icon_spans", 0x81310u, 0x11310u, 0x6a4u, 0x6a4u, 2, 8, 1, 1 },
  { "g_held_item_icon_width", 0x819b4u, 0x119b4u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_held_item_slide_timer", 0x819bcu, 0x119bcu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_player_locomotion_flags", 0x819c0u, 0x119c0u, 0x1u, 0x1u, 0, 8, 1, 1 },
  { "g_player_airborne", 0x819c1u, 0x119c1u, 0x4u, 0x17u, 0, 32, 1, 1 },
  { "g_entity_def_cache_head", 0x819d8u, 0x119d8u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_entity_def_cache_nodes", 0x819dcu, 0x119dcu, 0x438u, 0x438u, 2, 8, 1, 1 },
  { "g_entity_def_cache_count", 0x81e14u, 0x11e14u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_dbase100_base", 0x81e1cu, 0x11e1cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dbase100_inventory_table", 0x81e20u, 0x11e20u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dbase100_dialogue_table", 0x81e24u, 0x11e24u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dbase100_record_bitmap", 0x81e28u, 0x11e28u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_value_reduction_factor", 0x81e30u, 0x11e30u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_object_select_easy_flag", 0x81e34u, 0x11e34u, 0xau, 0xau, 2, 8, 1, 1 },
  { "g_dialogue_action_queue_count", 0x81e3eu, 0x11e3eu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dialogue_action_queue", 0x81e42u, 0x11e42u, 0x60u, 0x60u, 1, 32, 1, 1 },
  { "g_dbase100_choice_cursor", 0x81ea2u, 0x11ea2u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dbase100_choice_remaining", 0x81ea6u, 0x11ea6u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dbase100_choice_mode", 0x81eaau, 0x11eaau, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dbase100_choice_count", 0x81eaeu, 0x11eaeu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dbase100_pending_topic", 0x81eb2u, 0x11eb2u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dbase100_choice_record_indices", 0x81eb6u, 0x11eb6u, 0x4cu, 0x4cu, 2, 8, 1, 1 },
  { "g_object_template_flags", 0x81f02u, 0x11f02u, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_dbase200_filename", 0x81f06u, 0x11f06u, 0x80u, 0x80u, 2, 8, 1, 1 },
  { "g_dbase300_filename", 0x81f86u, 0x11f86u, 0x80u, 0x80u, 2, 8, 1, 1 },
  { "g_cutscenes_seen_count", 0x82006u, 0x12006u, 0x6u, 0x6u, 2, 8, 1, 1 },
  { "g_voice_stream_state", 0x8200cu, 0x1200cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_voice_file_handle", 0x82010u, 0x12010u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_voice_stop_handle", 0x82014u, 0x12014u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_voice_bytes_remaining", 0x82018u, 0x12018u, 0x4u, 0x1cu, 0, 32, 1, 1 },
  { "g_voice_is_dpcm", 0x82034u, 0x12034u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_voice_dpcm_predictor", 0x82038u, 0x12038u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_timed_message_color", 0x82040u, 0x12040u, 0x1u, 0x1u, 0, 8, 1, 1 },
  { "g_voice_sample_rate", 0x82041u, 0x12041u, 0x4u, 0x78u, 0, 32, 1, 1 },
  { "g_voice_refill_pending", 0x820b9u, 0x120b9u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_message_cache_head", 0x820c1u, 0x120c1u, 0x404u, 0x404u, 1, 32, 1, 1 },
  { "g_dialogue_script_handle", 0x824c5u, 0x124c5u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_timed_message_lines", 0x824c9u, 0x124c9u, 0x118u, 0x118u, 1, 32, 1, 1 },
  { "g_timed_message_text_buffer", 0x825e1u, 0x125e1u, 0x200u, 0x200u, 2, 8, 1, 1 },
  { "g_timed_message_line_count", 0x827e1u, 0x127e1u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_timed_message_timer", 0x827e5u, 0x127e5u, 0x4u, 0x18u, 0, 32, 1, 1 },
  { "g_dialogue_segments", 0x827fdu, 0x127fdu, 0xcu, 0xcu, 2, 8, 1, 1 },
  { "g_dialogue_timer_rate", 0x82809u, 0x12809u, 0x4u, 0x90cu, 0, 32, 1, 1 },
  { "g_active_dialogue_context", 0x83115u, 0x13115u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dialogue_line_dwell", 0x83119u, 0x13119u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dialogue_dwell_divisor", 0x8311du, 0x1311du, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dialogue_segment_index", 0x83121u, 0x13121u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_move_freeze_gate", 0x83125u, 0x13125u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dialogue_reveal_ramp", 0x83129u, 0x13129u, 0x4u, 0x20u, 0, 32, 1, 1 },
  { "g_choice_option_records", 0x83149u, 0x13149u, 0x40u, 0x40u, 2, 8, 1, 1 },
  { "g_choice_line_records", 0x83189u, 0x13189u, 0x140u, 0x140u, 2, 8, 1, 1 },
  { "g_choice_text_buffer", 0x832c9u, 0x132c9u, 0x800u, 0x800u, 2, 8, 1, 1 },
  { "g_choice_line_count", 0x83ac9u, 0x13ac9u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_choice_interaction_mode", 0x83acdu, 0x13acdu, 0x4u, 0x18u, 0, 32, 1, 1 },
  { "g_choice_reveal_ramp", 0x83ae5u, 0x13ae5u, 0x4u, 0x5u, 0, 32, 1, 1 },
  { "g_dialogue_busy_flag", 0x83aeau, 0x13aeau, 0x4u, 0x186u, 0, 32, 1, 1 },
  { "g_cutscene_overlay_active", 0x83c70u, 0x13c70u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_cutscene_image_handle", 0x83c74u, 0x13c74u, 0x4u, 0xa4u, 0, 32, 1, 1 },
  { "g_screen_backup_handle", 0x83d18u, 0x13d18u, 0x4u, 0xcu, 0, 32, 1, 1 },
  { "g_saved_movement_enabled", 0x83d24u, 0x13d24u, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_message_resource_handle", 0x83d28u, 0x13d28u, 0x4u, 0x44u, 0, 32, 1, 1 },
  { "g_hud_weapon_das_handle", 0x83d6cu, 0x13d6cu, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_hud_panel_das_handle0", 0x83d74u, 0x13d74u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_hud_panel_das_handle1", 0x83d78u, 0x13d78u, 0x4u, 0xcu, 0, 32, 1, 1 },
  { "g_weapon_hud_anim_table", 0x83d84u, 0x13d84u, 0x80u, 0x80u, 2, 8, 1, 1 },
  { "g_weapon_hud_anim_count", 0x83e04u, 0x13e04u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_weapon_hud_anim_accum", 0x83e08u, 0x13e08u, 0x4u, 0x64u, 0, 32, 1, 1 },
  { "g_active_weapon_ammo", 0x83e6cu, 0x13e6cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_active_weapon_item_id", 0x83e70u, 0x13e70u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_active_weapon_ammo_cap", 0x83e74u, 0x13e74u, 0x20u, 0x20u, 2, 8, 1, 1 },
  { "g_voice_decode_suspended", 0x83e94u, 0x13e94u, 0x4u, 0xcu, 0, 32, 1, 1 },
  { "g_menu_frontend_flag", 0x83ea0u, 0x13ea0u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_playback_menu_scroll_anchor", 0x83ea4u, 0x13ea4u, 0x4u, 0xcu, 0, 32, 1, 1 },
  { "g_entity_sound_emitter", 0x83eb0u, 0x13eb0u, 0x24u, 0x24u, 2, 8, 1, 1 },
  { "g_active_sound_handles", 0x83ed4u, 0x13ed4u, 0x9a0u, 0x9a0u, 1, 32, 1, 1 },
  { "g_sound_voice_descriptors", 0x84874u, 0x14874u, 0x80u, 0x80u, 2, 8, 1, 1 },
  { "g_sound_sample_table", 0x848f4u, 0x148f4u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_sound_bank_file_handle", 0x848f8u, 0x148f8u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_sound_sample_count", 0x848fcu, 0x148fcu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_voice_sos_callback", 0x84900u, 0x14900u, 0x4u, 0x6u, 0, 32, 1, 1 },
  { "g_pending_sound_param", 0x84906u, 0x14906u, 0x1u, 0x17u, 0, 8, 1, 1 },
  { "g_format_flags", 0x8491du, 0x1491du, 0x1u, 0x27u, 0, 8, 1, 1 },
  { "g_current_decoded_frame", 0x84944u, 0x14944u, 0x1u, 0x38u, 0, 8, 1, 1 },
  { "g_view_floor_clearance", 0x8497cu, 0x1497cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_render_source_base_ptr", 0x84980u, 0x14980u, 0x4u, 0xcu, 0, 32, 1, 1 },
  { "g_door_worklist", 0x8498cu, 0x1498cu, 0x4u, 0x10u, 0, 32, 1, 1 },
  { "g_current_proc_tag", 0x8499cu, 0x1499cu, 0x4u, 0x17cu, 0, 32, 1, 1 },
  { "g_secondary_surface_list", 0x84b18u, 0x14b18u, 0x400u, 0x400u, 2, 8, 1, 1 },
  { "g_world_span_record", 0x84f18u, 0x14f18u, 0x16u, 0x16u, 2, 8, 1, 0 },
  { "g_span_fill_mode_word", 0x84f2eu, 0x14f2eu, 0x2u, 0x2f2u, 0, 16, 1, 1 },
  { "g_visible_extent_count", 0x85220u, 0x15220u, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_visible_extent_list", 0x85224u, 0x15224u, 0x40u, 0x40u, 1, 16, 1, 1 },
  { "g_view_clip_plane", 0x85264u, 0x15264u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_view_bounds_rect", 0x8526cu, 0x1526cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_view_params_block", 0x85270u, 0x15270u, 0x4u, 0x18u, 0, 32, 1, 1 },
  { "g_perspective_scale", 0x85288u, 0x15288u, 0x4u, 0xcu, 0, 32, 1, 1 },
  { "g_map_geometry_selector", 0x85294u, 0x15294u, 0x2u, 0x20u, 0, 16, 1, 1 },
  { "g_world_span_bottom", 0x852b4u, 0x152b4u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_world_span_top", 0x852b6u, 0x152b6u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_face_span_bottom", 0x852b8u, 0x152b8u, 0x2u, 0x2u, 2, 8, 1, 1 },
  { "g_face_span_top", 0x852bau, 0x152bau, 0x2u, 0x8u, 0, 16, 1, 1 },
  { "g_span_gouraud_colour_a", 0x852c2u, 0x152c2u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_span_gouraud_colour_b", 0x852c4u, 0x152c4u, 0x2u, 0x4u, 0, 16, 1, 1 },
  { "g_surface_record_selector", 0x852c8u, 0x152c8u, 0x2u, 0x4u, 0, 16, 1, 1 },
  { "g_vertex_selector", 0x852ccu, 0x152ccu, 0x2u, 0x2eu, 0, 16, 1, 1 },
  { "g_sector_cull_coord", 0x852fau, 0x152fau, 0x2u, 0x16u, 0, 16, 1, 1 },
  { "g_camera_sin", 0x85310u, 0x15310u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_camera_cos", 0x85312u, 0x15312u, 0x2u, 0x6u, 0, 16, 1, 1 },
  { "g_secondary_surface_count", 0x85318u, 0x15318u, 0x2u, 0x8u, 0, 16, 1, 1 },
  { "g_last_frame_tick", 0x85320u, 0x15320u, 0x2u, 0x4u, 0, 16, 1, 1 },
  { "g_frame_time_scale", 0x85324u, 0x15324u, 0x6u, 0x6u, 2, 8, 1, 1 },
  { "g_anim_clock", 0x8532au, 0x1532au, 0x2u, 0x16u, 0, 16, 1, 1 },
  { "g_reflection_view_count", 0x85340u, 0x15340u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_reflection_view_list", 0x85344u, 0x15344u, 0x8cu, 0x8cu, 2, 8, 1, 0 },
  { "g_has_secondary_surfaces", 0x853d0u, 0x153d0u, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_secondary_subpass_flags", 0x853d2u, 0x153d2u, 0x1u, 0x1u, 0, 8, 1, 1 },
  { "g_render_sector_walk_mode", 0x853d3u, 0x153d3u, 0x1u, 0x26u, 0, 8, 1, 1 },
  { "g_secondary_subpass_id", 0x853f9u, 0x153f9u, 0x1u, 0x7u, 0, 8, 1, 1 },
  { "g_das_eviction_protected_allocation", 0x85400u, 0x15400u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_das_render_scale", 0x85404u, 0x15404u, 0x4u, 0x10u, 0, 32, 1, 1 },
  { "g_render_target_buffer", 0x85414u, 0x15414u, 0x4u, 0x24u, 0, 32, 1, 1 },
  { "g_map_buffer_pitch", 0x85438u, 0x15438u, 0x4u, 0x4u, 2, 8, 1, 0 },
  { "g_map_buffer_base", 0x8543cu, 0x1543cu, 0x4u, 0x4u, 2, 8, 1, 0 },
  { "g_map_scale_x", 0x85440u, 0x15440u, 0x4u, 0x4u, 2, 8, 1, 0 },
  { "g_map_scale_y", 0x85444u, 0x15444u, 0x14u, 0x14u, 2, 8, 1, 0 },
  { "g_map_draw_color", 0x85458u, 0x15458u, 0x2u, 0x2u, 2, 8, 1, 0 },
  { "g_map_world_center_x", 0x8545au, 0x1545au, 0x2u, 0x2u, 2, 8, 1, 0 },
  { "g_map_world_center_y", 0x8545cu, 0x1545cu, 0x2u, 0x2u, 2, 8, 1, 0 },
  { "g_map_screen_center_y", 0x8545eu, 0x1545eu, 0x2u, 0x2u, 2, 8, 1, 0 },
  { "g_map_screen_center_x", 0x85460u, 0x15460u, 0x18u, 0x18u, 2, 8, 1, 0 },
  { "g_framebuffer_bytes", 0x85478u, 0x15478u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_warp_dest_a", 0x8547cu, 0x1547cu, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_warp_dest_b", 0x85480u, 0x15480u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_map_first_load_flag", 0x85484u, 0x15484u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_palette_rgb_ptr", 0x85488u, 0x15488u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_audio_decode_buffer_a", 0x8548cu, 0x1548cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_audio_decode_buffer_b", 0x85490u, 0x15490u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_audio_silence_buffer", 0x85494u, 0x15494u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_screen_pitch", 0x85498u, 0x15498u, 0x8u, 0x8u, 2, 8, 1, 1 },
  { "g_screen_height", 0x854a0u, 0x154a0u, 0x8u, 0x8u, 2, 8, 1, 1 },
  { "g_scanline_dest_offset_table", 0x854a8u, 0x154a8u, 0x780u, 0x780u, 1, 32, 1, 1 },
  { "g_object_buffer_free", 0x85c28u, 0x15c28u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_object_table_header", 0x85c30u, 0x15c30u, 0x4u, 0xcu, 0, 32, 1, 1 },
  { "g_das_cache_heap_handle", 0x85c3cu, 0x15c3cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_resource_pool", 0x85c40u, 0x15c40u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_sfx_nodes", 0x85c44u, 0x15c44u, 0x4u, 0xcu, 0, 32, 1, 1 },
  { "g_das_collision_buffer", 0x85c50u, 0x15c50u, 0x4u, 0x88u, 0, 32, 1, 1 },
  { "g_view_w", 0x85cd8u, 0x15cd8u, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_view_h", 0x85cdcu, 0x15cdcu, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_view_x", 0x85ce0u, 0x15ce0u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_view_y", 0x85ce4u, 0x15ce4u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_map_das_dir_table_buffer", 0x85ce8u, 0x15ce8u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_ademo_das_fat_buffer", 0x85cf0u, 0x15cf0u, 0x4u, 0x10u, 0, 32, 1, 1 },
  { "g_das_file_handle", 0x85d00u, 0x15d00u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_das_remap_chunk_10000_ptr", 0x85d08u, 0x15d08u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_das_remap_chunk_100_a_ptr", 0x85d10u, 0x15d10u, 0x4u, 0x4u, 2, 8, 1, 0 },
  { "g_texture_flat_color_table", 0x85d14u, 0x15d14u, 0x1000u, 0x1000u, 2, 8, 1, 1 },
  { "g_das_remap_chunk_4000_ptr", 0x86d14u, 0x16d14u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_world_glow_table_ptr", 0x86d18u, 0x16d18u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_world_tint_table_ptr", 0x86d1cu, 0x16d1cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_das_remap_chunk_100_b_ptr", 0x86d20u, 0x16d20u, 0x8u, 0x8u, 2, 8, 1, 0 },
  { "g_world_shading_table_ptr", 0x86d28u, 0x16d28u, 0x8u, 0x8u, 1, 32, 1, 1 },
  { "g_das_entry_status_table", 0x86d30u, 0x16d30u, 0x2c00u, 0x2c00u, 1, 16, 1, 1 },
  { "g_das_cache_slots", 0x89930u, 0x19930u, 0x5dcu, 0x5dcu, 1, 32, 1, 1 },
  { "g_roth_error_code", 0x89f0cu, 0x19f0cu, 0x4u, 0x4u, 1, 16, 1, 1 },
  { "g_das_palette_remap_prefix", 0x89f10u, 0x19f10u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_gamma_level", 0x89f12u, 0x19f12u, 0x16u, 0x16u, 1, 16, 1, 1 },
  { "g_render_target_selector_secondary", 0x89f28u, 0x19f28u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_render_target_secondary_height", 0x89f2au, 0x19f2au, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_render_target_secondary_size", 0x89f2cu, 0x19f2cu, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_das_special_fat_index", 0x89f34u, 0x19f34u, 0x4u, 0x4u, 1, 16, 1, 1 },
  { "g_render_active", 0x89f38u, 0x19f38u, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_framebuffer_from_dos_block", 0x89f3au, 0x19f3au, 0x1u, 0x1u, 0, 8, 1, 1 },
  { "g_damage_flash_level", 0x89f3bu, 0x19f3bu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_das_skip_palette_load_flag", 0x89f3fu, 0x19f3fu, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_resource_pool_small_flag", 0x89f41u, 0x19f41u, 0x1u, 0x13u, 0, 8, 1, 1 },
  { "g_player_speed_reduction_request", 0x89f54u, 0x19f54u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_player_speed_reduction_shift", 0x89f58u, 0x19f58u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_state_record_list_count", 0x89f5cu, 0x19f5cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_item_autoselected_flag", 0x89f60u, 0x19f60u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_if_item_list_count", 0x89f64u, 0x19f64u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_if_item_list", 0x89f68u, 0x19f68u, 0x40u, 0x40u, 2, 8, 1, 0 },
  { "g_last_item_record", 0x89fa8u, 0x19fa8u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_item_drop_position", 0x89facu, 0x19facu, 0x12cu, 0x12cu, 1, 16, 1, 1 },
  { "g_object_ptr_array", 0x8a0d8u, 0x1a0d8u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_pending_command_record", 0x8a0dcu, 0x1a0dcu, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_state_link_obj_ptr", 0x8a0e4u, 0x1a0e4u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_state_link_word_a", 0x8a0e8u, 0x1a0e8u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_state_link_word_b", 0x8a0ecu, 0x1a0ecu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_player_health", 0x8a0f0u, 0x1a0f0u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_active_object", 0x8a0f8u, 0x1a0f8u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_command_source_object", 0x8a100u, 0x1a100u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_anim_step_mode", 0x8a104u, 0x1a104u, 0x4u, 0x14u, 0, 32, 1, 1 },
  { "g_active_effect_pool", 0x8a118u, 0x1a118u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_effect_list_b", 0x8a11cu, 0x1a11cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_damage_emitter_ptr", 0x8a120u, 0x1a120u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_player_move_delta_x", 0x8a124u, 0x1a124u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_player_move_delta_y", 0x8a128u, 0x1a128u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_player_move_delta_z", 0x8a12cu, 0x1a12cu, 0x10u, 0x10u, 2, 8, 1, 1 },
  { "g_state_link_buf_ptr", 0x8a13cu, 0x1a13cu, 0x4u, 0x12cu, 0, 32, 1, 1 },
  { "g_command_chain_interrupt", 0x8a268u, 0x1a268u, 0x1u, 0x8u, 0, 8, 1, 1 },
  { "g_block_list_head", 0x8a270u, 0x1a270u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_pool_check_enabled", 0x8a278u, 0x1a278u, 0x4u, 0x30u, 0, 32, 1, 1 },
  { "g_active_world_remap_selector", 0x8a2a8u, 0x1a2a8u, 0x2u, 0x4u, 0, 16, 1, 1 },
  { "g_active_world_remap_base", 0x8a2acu, 0x1a2acu, 0x4u, 0x10u, 0, 32, 1, 1 },
  { "g_world_span_fn", 0x8a2bcu, 0x1a2bcu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_world_span_fn2", 0x8a2c0u, 0x1a2c0u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_world_span_fn_alt", 0x8a2c4u, 0x1a2c4u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_world_span_fn_alt2", 0x8a2c8u, 0x1a2c8u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_span_endpoint_a", 0x8a2ccu, 0x1a2ccu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_span_endpoint_a_colstep", 0x8a2d0u, 0x1a2d0u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_span_endpoint_b", 0x8a2d4u, 0x1a2d4u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_span_endpoint_b_colstep", 0x8a2d8u, 0x1a2d8u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_span_accum_init", 0x8a2dcu, 0x1a2dcu, 0x1u, 0x1u, 2, 8, 1, 1 },
  { "g_span_shade_seed", 0x8a2ddu, 0x1a2ddu, 0x1u, 0x3u, 0, 8, 1, 1 },
  { "g_span_pixel_step", 0x8a2e0u, 0x1a2e0u, 0x4u, 0x2u, 0, 32, 1, 0 },
  { "g_span_eax_step_lo", 0x8a2e2u, 0x1a2e2u, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_wall_vstep", 0x8a2e4u, 0x1a2e4u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_span_texU_accum", 0x8a2ecu, 0x1a2ecu, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_span_texV_accum", 0x8a2f0u, 0x1a2f0u, 0x4u, 0x20u, 0, 32, 1, 1 },
  { "g_render_double_scanline_flag", 0x8a310u, 0x1a310u, 0x1u, 0x6u, 0, 8, 1, 1 },
  { "g_span_round_half", 0x8a316u, 0x1a316u, 0x2u, 0x1eu, 0, 16, 1, 1 },
  { "g_wall_render_flags", 0x8a334u, 0x1a334u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_wall_segment_width", 0x8a336u, 0x1a336u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_span_src_wrap_base", 0x8a338u, 0x1a338u, 0x4u, 0xcu, 0, 32, 1, 1 },
  { "g_span_eax_accum_init", 0x8a344u, 0x1a344u, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_wall_column_count", 0x8a348u, 0x1a348u, 0x2u, 0x4u, 0, 16, 1, 1 },
  { "g_span_draw_mode_flags", 0x8a34cu, 0x1a34cu, 0x1u, 0x6u, 0, 8, 1, 1 },
  { "g_span_textured_mode_flag", 0x8a352u, 0x1a352u, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_span_blend_mode_flag", 0x8a354u, 0x1a354u, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_render_x_flip_flag", 0x8a356u, 0x1a356u, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_sprite_span_remaining", 0x8a358u, 0x1a358u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_sprite_perspective_step", 0x8a35cu, 0x1a35cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_sprite_tex_step_frac", 0x8a360u, 0x1a360u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_sprite_column_fn", 0x8a368u, 0x1a368u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_current_span_record", 0x8a36cu, 0x1a36cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_sprite_column_loop_guard", 0x8a370u, 0x1a370u, 0x4u, 0x2u, 0, 32, 1, 0 },
  { "g_sprite_span_width", 0x8a372u, 0x1a372u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_sprite_src_coord", 0x8a374u, 0x1a374u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_sprite_src_coord_step", 0x8a378u, 0x1a378u, 0x4u, 0x14u, 0, 32, 1, 1 },
  { "g_sprite_tex_step_u", 0x8a38cu, 0x1a38cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_sprite_tex_step_u2", 0x8a390u, 0x1a390u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_sprite_tex_step_v", 0x8a394u, 0x1a394u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_sprite_tex_step_v2", 0x8a398u, 0x1a398u, 0x4u, 0x14u, 0, 32, 1, 1 },
  { "g_sprite_span_flip", 0x8a3acu, 0x1a3acu, 0xeu, 0xeu, 2, 8, 1, 1 },
  { "g_sprite_span_shade", 0x8a3bau, 0x1a3bau, 0x1u, 0x6u, 0, 8, 1, 1 },
  { "g_floorceil_span_fn", 0x8a3c0u, 0x1a3c0u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_floorceil_span_fn_alt", 0x8a3c4u, 0x1a3c4u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_clip_output_vertex_count", 0x8a3ccu, 0x1a3ccu, 0x4u, 0x10u, 0, 32, 1, 1 },
  { "g_floorceil_accum_a", 0x8a3dcu, 0x1a3dcu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_floorceil_accum_b", 0x8a3e0u, 0x1a3e0u, 0x14u, 0x14u, 2, 8, 1, 1 },
  { "g_floorceil_step_a", 0x8a3f4u, 0x1a3f4u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_floorceil_step_b", 0x8a3f8u, 0x1a3f8u, 0x4u, 0x3cu, 0, 32, 1, 1 },
  { "g_floorceil_clip_flags", 0x8a434u, 0x1a434u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_clip_boundary", 0x8a436u, 0x1a436u, 0x2u, 0x4u, 0, 16, 1, 1 },
  { "g_floorceil_edge_orientation", 0x8a43au, 0x1a43au, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_floorceil_edge_x_end", 0x8a43cu, 0x1a43cu, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_floorceil_edge_x_start", 0x8a43eu, 0x1a43eu, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_floorceil_edge_emitted", 0x8a440u, 0x1a440u, 0x2u, 0x606u, 0, 16, 1, 1 },
  { "g_atan_table", 0x8aa46u, 0x1aa46u, 0x2u, 0x8au, 0, 16, 1, 1 },
  { "g_sprite_node_pool", 0x8aad0u, 0x1aad0u, 0x870u, 0x870u, 2, 8, 1, 0 },
  { "g_sprite_render_queue_head", 0x8b340u, 0x1b340u, 0x4u, 0x1cu, 0, 32, 1, 1 },
  { "g_snapshot_work_buf", 0x8b35cu, 0x1b35cu, 0x4u, 0x14u, 0, 32, 1, 1 },
  { "g_snapshot_filename_buf", 0x8b370u, 0x1b370u, 0x84u, 0x84u, 2, 8, 1, 1 },
  { "g_door_count", 0x8b3f4u, 0x1b3f4u, 0x1u, 0x4u, 0, 8, 1, 1 },
  { "g_door_pool", 0x8b3f8u, 0x1b3f8u, 0x2u, 0x2u, 2, 8, 1, 1 },
  { "g_door_state_table", 0x8b3fau, 0x1b3fau, 0xbc2u, 0xbc2u, 2, 8, 1, 0 },
  { "g_secondary_door_count", 0x8bfbcu, 0x1bfbcu, 0x1u, 0x4u, 0, 8, 1, 1 },
  { "g_secondary_door_pool", 0x8bfc0u, 0x1bfc0u, 0x118u, 0x118u, 2, 8, 1, 1 },
  { "g_collision_move_entity_geom", 0x8c0d8u, 0x1c0d8u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_collision_move_entity", 0x8c0dcu, 0x1c0dcu, 0x4u, 0x10u, 0, 32, 1, 1 },
  { "g_collision_target_radius", 0x8c0ecu, 0x1c0ecu, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_collision_target_active", 0x8c0f0u, 0x1c0f0u, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_collision_hit_entity", 0x8c0f4u, 0x1c0f4u, 0x4u, 0x14u, 0, 32, 1, 1 },
  { "g_view_pitch_applied", 0x8c108u, 0x1c108u, 0x8u, 0x8u, 1, 32, 1, 1 },
  { "g_player_height", 0x8c110u, 0x1c110u, 0x2u, 0x10u, 0, 16, 1, 1 },
  { "g_locate_query_x", 0x8c120u, 0x1c120u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_locate_query_z", 0x8c124u, 0x1c124u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_locate_query_y", 0x8c128u, 0x1c128u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_collision_entity_count", 0x8c12cu, 0x1c12cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_collision_box_max", 0x8c130u, 0x1c130u, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_collision_box_min", 0x8c134u, 0x1c134u, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_collision_radius_sq", 0x8c138u, 0x1c138u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_collision_corner_radius_sq", 0x8c140u, 0x1c140u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_collision_radius", 0x8c144u, 0x1c144u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_max_climb", 0x8c148u, 0x1c148u, 0x2u, 0x24u, 0, 16, 1, 1 },
  { "g_collision_blocker_object", 0x8c16cu, 0x1c16cu, 0x4u, 0x24u, 0, 32, 1, 1 },
  { "g_collision_portal_continue", 0x8c190u, 0x1c190u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_collision_sector_stack_count", 0x8c192u, 0x1c192u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_collision_sector_stack", 0x8c194u, 0x1c194u, 0x42u, 0x42u, 2, 8, 1, 1 },
  { "g_player_sector_cache", 0x8c1d6u, 0x1c1d6u, 0x2u, 0x8u, 0, 16, 1, 1 },
  { "g_viewmodel_shade_level", 0x8c1deu, 0x1c1deu, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_collision_hit_flags", 0x8c1e0u, 0x1c1e0u, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_collision_step_active", 0x8c1e2u, 0x1c1e2u, 0x1u, 0xdu, 0, 8, 1, 1 },
  { "g_collision_edge_ax", 0x8c1efu, 0x1c1efu, 0x2u, 0x2u, 2, 8, 1, 1 },
  { "g_collision_edge_ay", 0x8c1f1u, 0x1c1f1u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_collision_edge_bx", 0x8c1f3u, 0x1c1f3u, 0x2u, 0x2u, 2, 8, 1, 1 },
  { "g_collision_edge_by", 0x8c1f5u, 0x1c1f5u, 0x2u, 0x3u, 0, 16, 1, 1 },
  { "g_dos_transfer_buffer_linear", 0x8c1f8u, 0x1c1f8u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dos_transfer_buffer_selector", 0x8c1fcu, 0x1c1fcu, 0x2u, 0x4u, 0, 16, 1, 1 },
  { "g_projection_build_dir", 0x8c200u, 0x1c200u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_projection_table_backup", 0x8c204u, 0x1c204u, 0x280u, 0x280u, 2, 8, 1, 0 },
  { "g_render_column_source_table", 0x8c484u, 0x1c484u, 0x1u, 0x288u, 0, 8, 1, 1 },
  { "g_current_das_fat_entry", 0x8c70cu, 0x1c70cu, 0x4u, 0x20u, 0, 32, 1, 1 },
  { "g_current_das_block_size_bytes", 0x8c72cu, 0x1c72cu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_current_das_fat_index_x2", 0x8c730u, 0x1c730u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_current_das_cache_slot", 0x8c734u, 0x1c734u, 0x4u, 0x4u, 2, 8, 1, 0 },
  { "g_current_das_block_allocation", 0x8c738u, 0x1c738u, 0x4u, 0x4u, 2, 8, 1, 0 },
  { "g_current_das_alloc_size", 0x8c73cu, 0x1c73cu, 0x4u, 0x4u, 2, 8, 1, 0 },
  { "g_das_low_index_bitset", 0x8c740u, 0x1c740u, 0x200u, 0x200u, 2, 8, 1, 1 },
  { "g_current_das_cache_slot_index", 0x8c940u, 0x1c940u, 0x2u, 0x2u, 2, 8, 1, 1 },
  { "g_das_special_index_load_flag", 0x8c942u, 0x1c942u, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_floorceil_vertex_count", 0x8c944u, 0x1c944u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_floorceil_vertex_records", 0x8c946u, 0x1c946u, 0x3c6u, 0x3c6u, 2, 8, 1, 0 },
  { "g_floorceil_span_records", 0x8cd0cu, 0x1cd0cu, 0x3c30u, 0x3c30u, 2, 8, 1, 1 },
  { "g_world_surface_draw_flags", 0x9093cu, 0x2093cu, 0xcu, 0xcu, 2, 8, 1, 1 },
  { "g_wall_proj_y0", 0x90948u, 0x20948u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_wall_proj_y1", 0x9094au, 0x2094au, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_wall_proj_y2", 0x9094cu, 0x2094cu, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_wall_proj_y3", 0x9094eu, 0x2094eu, 0x2u, 0x1au, 0, 16, 1, 1 },
  { "g_view_bound_right", 0x90968u, 0x20968u, 0x2u, 0x2u, 2, 8, 1, 1 },
  { "g_view_bound_left", 0x9096au, 0x2096au, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_view_bound_bottom", 0x9096cu, 0x2096cu, 0x2u, 0x2u, 2, 8, 1, 1 },
  { "g_view_bound_top", 0x9096eu, 0x2096eu, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_column_clip_mode", 0x90970u, 0x20970u, 0x1u, 0x8u, 0, 8, 1, 1 },
  { "g_span_src_row_width", 0x90978u, 0x20978u, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_span_src_wrap_reoffset", 0x9097cu, 0x2097cu, 0x32u, 0x32u, 2, 8, 1, 1 },
  { "g_world_alt_render_flags", 0x909aeu, 0x209aeu, 0x2u, 0x4u, 0, 16, 1, 1 },
  { "g_floor_tex_caps", 0x909b2u, 0x209b2u, 0x2u, 0x46u, 0, 16, 1, 1 },
  { "g_sprite_view_angle", 0x909f8u, 0x209f8u, 0x2u, 0xcu, 0, 16, 1, 1 },
  { "g_view_offset_x", 0x90a04u, 0x20a04u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_view_offset_y", 0x90a06u, 0x20a06u, 0x2u, 0x18u, 0, 16, 1, 1 },
  { "g_floorceil_depth_clip_bias", 0x90a1eu, 0x20a1eu, 0x2u, 0x2u, 2, 8, 1, 1 },
  { "g_floorceil_clip_scale", 0x90a20u, 0x20a20u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_render_textured_flag", 0x90a22u, 0x20a22u, 0x2u, 0x2u, 2, 8, 1, 1 },
  { "g_sprite_fill_index", 0x90a24u, 0x20a24u, 0x4u, 0x4u, 2, 8, 1, 1 },
  { "g_span_clip_source", 0x90a28u, 0x20a28u, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_parallax_sky_active", 0x90a2au, 0x20a2au, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_world_span_colorkey", 0x90a2cu, 0x20a2cu, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_current_surface_render_flags", 0x90a2eu, 0x20a2eu, 0x2u, 0x2u, 2, 8, 1, 1 },
  { "g_sprite_render_mode", 0x90a30u, 0x20a30u, 0x1u, 0x4u, 0, 8, 1, 1 },
  { "g_span_callback", 0x90a34u, 0x20a34u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_map_das_fat_buffer", 0x90a38u, 0x20a38u, 0x4u, 0x10u, 0, 32, 1, 1 },
  { "g_world_render_subpass_kind", 0x90a48u, 0x20a48u, 0x8u, 0x8u, 2, 8, 1, 1 },
  { "g_subpass_surfrec_ref", 0x90a50u, 0x20a50u, 0xau, 0xau, 2, 8, 1, 1 },
  { "g_subpass_reflect_param_a", 0x90a5au, 0x20a5au, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_subpass_reflect_param_b", 0x90a5cu, 0x20a5cu, 0x2u, 0xcu, 0, 16, 1, 1 },
  { "g_subpass_persp_step", 0x90a68u, 0x20a68u, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_view_center_x", 0x90a70u, 0x20a70u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_view_center_y", 0x90a72u, 0x20a72u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_view_pitch", 0x90a74u, 0x20a74u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_current_das_entry_id", 0x90a78u, 0x20a78u, 0x8u, 0x8u, 2, 8, 1, 1 },
  { "g_player_vel_accum_x", 0x90a80u, 0x20a80u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_player_vel_accum_y", 0x90a84u, 0x20a84u, 0x4u, 0x6u, 0, 32, 1, 1 },
  { "g_player_angle", 0x90a8au, 0x20a8au, 0x2u, 0x4u, 0, 16, 1, 1 },
  { "g_player_x", 0x90a8eu, 0x20a8eu, 0x2u, 0x4u, 0, 16, 1, 1 },
  { "g_player_z", 0x90a92u, 0x20a92u, 0x2u, 0x4u, 0, 16, 1, 1 },
  { "g_player_y", 0x90a96u, 0x20a96u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_framebuffer_ptr", 0x90a98u, 0x20a98u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_image_surface", 0x90a9cu, 0x20a9cu, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_map_objects_buffer", 0x90aa4u, 0x20aa4u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_map_geometry_buffer", 0x90aa8u, 0x20aa8u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_sector_geom_base", 0x90aacu, 0x20aacu, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_collision_restore_x", 0x90ab4u, 0x20ab4u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_collision_restore_y", 0x90ab8u, 0x20ab8u, 0x4u, 0x6u, 0, 32, 1, 1 },
  { "g_vel_queue_a", 0x90abeu, 0x20abeu, 0x2u, 0x84u, 0, 16, 1, 1 },
  { "g_vel_queue_b", 0x90b42u, 0x20b42u, 0x2u, 0x8au, 0, 16, 1, 1 },
  { "g_frame_tick_counter", 0x90bccu, 0x20bccu, 0x2u, 0x8u, 0, 16, 1, 1 },
  { "g_view_scale_flags", 0x90bd4u, 0x20bd4u, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_vel_queue_select", 0x90bd6u, 0x20bd6u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_turn_accum", 0x90bd8u, 0x20bd8u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_player_move_rate_counter", 0x90bdau, 0x20bdau, 0x2u, 0x4u, 0, 16, 1, 1 },
  { "g_max_step_height", 0x90bdeu, 0x20bdeu, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_min_fit", 0x90be0u, 0x20be0u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_transparency_blend_selector", 0x90be2u, 0x20be2u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_vga_mode_configured", 0x90be4u, 0x20be4u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_video_mode_flags", 0x90be6u, 0x20be6u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_geometry_selector", 0x90be8u, 0x20be8u, 0x2u, 0xau, 0, 16, 1, 1 },
  { "g_render_width", 0x90bf2u, 0x20bf2u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_render_viewport_height", 0x90bf4u, 0x20bf4u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_render_height", 0x90bf6u, 0x20bf6u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_blur_flag", 0x90bf8u, 0x20bf8u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_antialias_mode", 0x90bfau, 0x20bfau, 0x2u, 0x2u, 2, 8, 1, 0 },
  { "g_render_viewport_reconfig", 0x90bfcu, 0x20bfcu, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_subpass_patch_gate", 0x90bfeu, 0x20bfeu, 0x2u, 0x6u, 0, 16, 1, 1 },
  { "g_flush_predraw_flag", 0x90c04u, 0x20c04u, 0x2u, 0x2u, 2, 8, 1, 1 },
  { "g_render_target_selector", 0x90c06u, 0x20c06u, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_rawscreen_flag", 0x90c08u, 0x20c08u, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_das_cache_tick", 0x90c0au, 0x20c0au, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_viewport_top_margin", 0x90c0cu, 0x20c0cu, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_text_color_ramp_selector", 0x90c0eu, 0x20c0eu, 0x4u, 0x4u, 1, 16, 1, 1 },
  { "g_player_sector", 0x90c12u, 0x20c12u, 0x2u, 0x8u, 0, 16, 1, 1 },
  { "g_render_shade_level", 0x90c1au, 0x20c1au, 0x2u, 0x22u, 0, 16, 1, 1 },
  { "g_key_state_bitmap", 0x90c3cu, 0x20c3cu, 0x1u, 0x6u, 0, 8, 1, 1 },
  { "g_key_modifier_flags", 0x90c42u, 0x20c42u, 0x1u, 0x7bu, 0, 8, 1, 1 },
  { "g_hires_line_doubling_flag", 0x90cbdu, 0x20cbdu, 0x1u, 0x1u, 0, 8, 1, 1 },
  { "g_das_unk_0x22", 0x90cbeu, 0x20cbeu, 0x2u, 0x2u, 0, 16, 1, 1 },
  { "g_turn_view_scale_state", 0x90cc0u, 0x20cc0u, 0x1u, 0x4u, 0, 8, 1, 1 },
  { "g_flat_shading_flag", 0x90cc4u, 0x20cc4u, 0x1u, 0x284u, 0, 8, 1, 1 },
  { "g_dta_initialized", 0x90f48u, 0x20f48u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dos_dta", 0x90f4cu, 0x20f4cu, 0x1eu, 0x1eu, 2, 8, 1, 1 },
  { "g_dos_dta_name", 0x90f6au, 0x20f6au, 0x72u, 0x72u, 2, 8, 1, 1 },
  { "g_projectile_collision_width", 0x90fdcu, 0x20fdcu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dynamic_entity_count", 0x90fe0u, 0x20fe0u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_dynamic_entity_table", 0x90fe4u, 0x20fe4u, 0x1e1u, 0x1e1u, 2, 8, 1, 1 },
  { "g_object_table_dirty", 0x911c5u, 0x211c5u, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_object_table_generation", 0x911c7u, 0x211c7u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_spawn_projectile_is_player", 0x911cbu, 0x211cbu, 0x1u, 0x5u, 0, 8, 1, 1 },
  { "g_saved_int24_vector", 0x911d0u, 0x211d0u, 0x4u, 0xcu, 0, 32, 1, 1 },
  { "g_sfx_query_capacity", 0x911dcu, 0x211dcu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_sfx_query_result_count", 0x911e0u, 0x211e0u, 0x4u, 0x684u, 0, 32, 1, 1 },
  { "g_particle_pool", 0x91864u, 0x21864u, 0x4u, 0x40u, 0, 32, 1, 1 },
  { "g_dpcm_step_table", 0x918a4u, 0x218a4u, 0x45cu, 0x45cu, 1, 32, 1, 1 },
  { "g_gdv_user_callback", 0x91d00u, 0x21d00u, 0x4u, 0xcu, 0, 32, 1, 1 },
  { "g_gdv_stream_flags", 0x91d0cu, 0x21d0cu, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_gdv_context", 0x91d14u, 0x21d14u, 0x4u, 0x18u, 0, 32, 1, 1 },
  { "g_gdv_audio_buf_size", 0x91d2cu, 0x21d2cu, 0x4u, 0x8u, 0, 32, 1, 1 },
  { "g_gdv_decode_buffer", 0x91d34u, 0x21d34u, 0x4u, 0x1cu, 0, 32, 1, 1 },
  { "g_gdv_audio_stream_base", 0x91d50u, 0x21d50u, 0x4u, 0x78u, 0, 32, 1, 1 },
  { "g_gdv_audio_enabled", 0x91dc8u, 0x21dc8u, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_gdv_audio_format", 0x91dcau, 0x21dcau, 0x1u, 0x12u, 0, 8, 1, 1 },
  { "g_gdv_decoder_active", 0x91ddcu, 0x21ddcu, 0x1u, 0x2u, 0, 8, 1, 1 },
  { "g_gdv_end_of_stream", 0x91ddeu, 0x21ddeu, 0x1u, 0x8u, 0, 8, 1, 1 },
  { "g_palette_dirty", 0x91de6u, 0x21de6u, 0x1u, 0xeu, 0, 8, 1, 1 },
  { "g_gdv_audio_end", 0x91df4u, 0x21df4u, 0x1u, 0x4u, 0, 8, 1, 1 },
  { "g_sector_count", 0x91df8u, 0x21df8u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_sector_section_offset", 0x91dfcu, 0x21dfcu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_state_pool_a_count", 0x91e00u, 0x21e00u, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_state_pool_a_records", 0x91e04u, 0x21e04u, 0x2b0u, 0x2b0u, 2, 8, 1, 1 },
  { "g_sos_driver_active", 0x920b4u, 0x220b4u, 0x3cu, 0x3cu, 2, 8, 1, 0 },
  { "g_sos_driver_type_ids", 0x920f0u, 0x220f0u, 0xeacu, 0xeacu, 2, 8, 1, 1 },
  { "g_sos_driver_vtable", 0x92f9cu, 0x22f9cu, 0x1c8u, 0x1c8u, 2, 8, 1, 0 },
  { "g_sos_driver_descriptor", 0x93164u, 0x23164u, 0x30u, 0x30u, 2, 8, 1, 1 },
  { "g_sos_drivers_installed", 0x93194u, 0x23194u, 0x4u, 0x24u, 0, 32, 1, 1 },
  { "g_extmidi_out_callback", 0x931b8u, 0x231b8u, 0x1ffcu, 0x1ffcu, 2, 8, 1, 0 },
  { "g_sos_midi_message", 0x951b4u, 0x251b4u, 0x18u, 0x18u, 2, 8, 1, 0 },
  { "g_sos_voice_alloc_mode", 0x951ccu, 0x251ccu, 0x4u, 0x4u, 0, 32, 1, 1 },
  { "g_sos_timer_tick_flag", 0x951d0u, 0x251d0u, 0x2270u, 0x2270u, 2, 8, 1, 0 },
  { "g_sos_voice_table", 0x97440u, 0x27440u, 0x584u, 0x584u, 2, 8, 1, 0 },
  { "g_sos_timer_event_table", 0x979c4u, 0x279c4u, 0x1a0u, 0x1a0u, 2, 8, 1, 0 },
  { "g_sos_timer_event_count", 0x97b64u, 0x27b64u, 0x1e0u, 0x1e0u, 2, 8, 1, 0 },
  { "errno", 0x97d44u, 0x27d44u, 0x4u, 0x4u, 2, 8, 1, 0 },
  { "_doserrno", 0x97d48u, 0x27d48u, 0x10428u, 0x10428u, 2, 8, 1, 0 },
};
const unsigned obj3_nsyms = 661u;

static int nfail;
static void sym_fail(const char *name, const char *what)
{ printf("  [FAIL] symbol %-40s %s\n", name, what); nfail++; }

int obj3_symbols_selfcheck(void)
{
    nfail = 0;
    /* per-symbol: the alias macro must resolve to base+off with the recorded size */
#define CHK(sym, off, sz) do { \
        if ((const volatile void *)&(sym) != \
            (const volatile void *)(OBJ3_SYMBASE + (off))) sym_fail(#sym, "address"); \
        if (sizeof(sym) != (sz)) sym_fail(#sym, "size"); \
    } while (0)
    /* OWNED symbol: real storage elsewhere — check size + that the built image
     * region equals the owning object's bytes (the overlay was applied). */
#define CHK_OWNED(sym, off, sz) do { \
        if (sizeof(sym) != (sz)) sym_fail(#sym, "size"); \
        if (memcmp((const void *)&(sym), \
                   (const void *)(OBJ3_SYMBASE + (off)), (sz))) \
            sym_fail(#sym, "owned storage != image region"); \
    } while (0)
    /* reloc-OWNED symbol: like CHK_OWNED but the reloc-slot ranges legitimately
     * differ (placeholder vs relocated pointer) — compare with those masked out. */
#define CHK_OWNED_RELOC(sym, sz, idx) do { \
        if (sizeof(sym) != (sz)) sym_fail(#sym, "size"); \
        if (obj3_owned_region_cmp(&obj3_owned_tab[idx], \
                                  (const unsigned char *)OBJ3_SYMBASE)) \
            sym_fail(#sym, "owned storage != image region (masked)"); \
    } while (0)
    CHK_OWNED(g_crt_data_seg_prefix, 0x0u, 0x10u);
    CHK_OWNED(g_default_response_file_msg, 0x10u, 0x17u);
    CHK_OWNED(g_startup_banner, 0x27u, 0x81u);
    CHK_OWNED(g_startup_device_msgs, 0xa8u, 0x64u);
    CHK_OWNED(g_msg_initiating_das, 0x10cu, 0x16u);
    CHK_OWNED(g_msg_direct_screen, 0x122u, 0x1fu);
    CHK_OWNED(g_msg_overscan_screen, 0x141u, 0x21u);
    CHK_OWNED(g_msg_detecting_vesa, 0x162u, 0x19u);
    CHK_OWNED(g_msg_hires_screen, 0x17bu, 0x1eu);
    CHK_OWNED(g_msg_blur_selected, 0x199u, 0x16u);
    CHK_OWNED(g_msg_starting_midi, 0x1afu, 0x18u);
    CHK_OWNED(g_msg_installing_sound, 0x1c7u, 0x1fu);
    CHK_OWNED(g_msg_ok, 0x1e6u, 0x6u);
    CHK_OWNED(g_cfg_file_arg, 0x1ecu, 0x50u);
    CHK_OWNED(g_cfg_das_arg, 0x23cu, 0x50u);
    CHK_OWNED(g_cfg_snd_arg, 0x28cu, 0x50u);
    CHK_OWNED(g_cfg_das2_arg, 0x2dcu, 0x1c9u);
    CHK_OWNED_RELOC(g_arg_command_table, 0x293u, 17);
    CHK_OWNED(g_snapshot_basename, 0x738u, 0xcu);
    CHK_OWNED(g_snapshot_name_seq, 0x744u, 0x2u);
    CHK_OWNED_RELOC(g_snapshot_anim_frame, 0x6du, 20);
    CHK_OWNED(g_mouse_x, 0x7b3u, 0x4u);
    CHK_OWNED(g_mouse_y, 0x7b7u, 0x4u);
    CHK_OWNED(g_pixel_extent_scale, 0x7bbu, 0x2u);
    CHK_OWNED(g_dbg_tilt_fmt, 0x7bdu, 0xcu);
    CHK_OWNED(g_kbd_dir_offset_table, 0x7c9u, 0x2u);
    CHK_OWNED(g_kbd_dir_offset_table_ext, 0x7cdu, 0x1cu);
    CHK_OWNED(g_keybit_mask_table, 0x7e9u, 0x1u);
    CHK_OWNED(g_keybit_mask_table_ext, 0x7eau, 0x7u);
    CHK_OWNED_RELOC(g_held_key_move_table, 0x3du, 29);
    CHK_OWNED(g_scancode_translate_table, 0x82eu, 0xb6u);
    CHK_OWNED(g_current_cursor_id, 0x8e4u, 0x2u);
    CHK_OWNED(g_cursor_mask_data, 0x8e6u, 0x57u);
    CHK_OWNED_RELOC(g_keymap_table, 0x5d5u, 33);
    CHK_OWNED(g_font_descriptor, 0xf12u, 0x2f6u);
    CHK_OWNED(g_ui_slot_layout_table, 0x1208u, 0x2u);
    CHK_OWNED(g_ui_slot_layout_table_ext, 0x120au, 0x2u);
    CHK_OWNED(g_ui_slot_layout_table_body, 0x120cu, 0x30u);
    CHK_OWNED_RELOC(g_inventory_tab_context_map, 0x12au, 38);
    CHK_OWNED(g_bit_mask_lut, 0x1366u, 0x1u);
    CHK_OWNED(g_bit_mask_lut_ext, 0x1367u, 0x9u);
    CHK_OWNED_RELOC(g_choice_selected_index, 0x68cu, 41);
    CHK_OWNED(g_mouse_speed, 0x19fcu, 0x138u);
    CHK_OWNED(g_vol_soundfx, 0x1b34u, 0xcu);
    CHK_OWNED(g_vol_speech, 0x1b40u, 0xcu);
    CHK_OWNED(g_vol_movie, 0x1b4cu, 0xcu);
    CHK_OWNED(g_vol_music, 0x1b58u, 0x1adu);
    CHK_OWNED(g_message_box_state, 0x1d05u, 0x41u);
    CHK_OWNED(g_gdv_error_strings, 0x1d46u, 0x4u);
    CHK_OWNED(g_test_sfx_descriptor, 0x1d4au, 0x4au);
    CHK_OWNED(g_hex_digits_lower, 0x1d94u, 0x10u);
    CHK_OWNED(g_hex_digits_upper, 0x1da4u, 0x10u);
    CHK_OWNED(g_shade_const_table_a, 0x1db4u, 0x2u);
    CHK_OWNED(g_shade_const_table_a_ext, 0x1db6u, 0x4u);
    CHK_OWNED(g_shade_const_table_b, 0x1dbau, 0x2u);
    CHK_OWNED(g_shade_const_table_b_ext, 0x1dbcu, 0x8u);
    CHK_OWNED(g_vesa_page_bank_offset, 0x1dc4u, 0x2u);
    CHK_OWNED(g_current_vesa_bank, 0x1dc6u, 0x6u);
    CHK_OWNED(g_vesa_available, 0x1dccu, 0x1u);
    CHK_OWNED(g_init_stage_error_strings, 0x1dd0u, 0x160u);
    CHK_OWNED_RELOC(g_anim_step_fn_table, 0x18u, 60);
    CHK_OWNED(g_command_rng, 0x1f48u, 0x4u);
    CHK_OWNED(g_msg_pool_damaged, 0x1f4cu, 0x34u);
    CHK_OWNED_RELOC(g_world_span_variant_table, 0x100u, 63);
    CHK_OWNED(g_sincos_table, 0x2080u, 0x400u);
    CHK_OWNED(g_snapshot_counter, 0x2480u, 0x2u);
    CHK_OWNED(g_snapshot_filenames, 0x2482u, 0x46u);
    CHK_OWNED(g_door_vertex_template, 0x24c8u, 0x2u);
    CHK_OWNED(g_door_vertex_template_body, 0x24cau, 0x26u);
    CHK_OWNED(g_player_walk_bob_table, 0x24f0u, 0x2u);
    CHK_OWNED(g_player_walk_bob_table_body, 0x24f2u, 0x42u);
    CHK_OWNED(g_heap_brk, 0x2534u, 0x4u);
    CHK_OWNED(g_response_file_arg, 0x2538u, 0x4u);
    CHK_OWNED(g_stack_limit, 0x2544u, 0x18u);
    CHK_OWNED(g_dos_child_running, 0x255cu, 0x6u);
    CHK_OWNED_RELOC(g_crt_memory_mode, 0x1cau, 75);
    CHK_OWNED(g_entity_damage_rng, 0x272cu, 0x4u);
    CHK_OWNED(g_ai_wander_rng, 0x2730u, 0x4u);
    CHK_OWNED(g_ai_anim_rng, 0x2734u, 0x4u);
    CHK_OWNED(g_ai_anim_rng_seed, 0x2738u, 0x4u);
    CHK_OWNED(g_actor_anim_scheduler, 0x273cu, 0x4u);
    CHK_OWNED(g_actor_move_rate, 0x2740u, 0x1u);
    CHK_OWNED(g_actor_tick_rate, 0x2744u, 0x4u);
    CHK_OWNED(g_actor_tick_rate_ext, 0x274cu, 0x20u);
    CHK_OWNED(g_rng_state, 0x276cu, 0x2u);
    CHK_OWNED(g_screen_mode_table, 0x2772u, 0x17eu);
    CHK_OWNED(g_index_class_table, 0x28f0u, 0x18u);
    CHK_OWNED(g_sos_sequence_ctx_table, 0x2908u, 0xd0u);
    CHK_OWNED(g_midi_logical_to_physical_chan, 0x29d8u, 0x2d0u);
    CHK_OWNED(g_midi_physical_to_logical_chan, 0x2ca8u, 0x50u);
    CHK_OWNED(g_midi_physical_chan_device, 0x2cf8u, 0x50u);
    CHK_OWNED(g_midi_channel_saved_state, 0x2d48u, 0x640u);
    CHK_OWNED(g_midi_channel_patch, 0x3388u, 0x330u);
    CHK_OWNED(g_midi_physical_chan_busy, 0x36b8u, 0x50u);
    CHK_OWNED(g_sound_master_volume, 0x3708u, 0x1u);
    CHK_OWNED(g_sound_channel_volume, 0x370cu, 0x20u);
    CHK_OWNED(g_midi_channel_raw_volume, 0x372cu, 0xaccu);
    CHK_OWNED(g_sos_timer_base_rate, 0x41f8u, 0x4u);
    CHK_OWNED_RELOC(g_sos_timer_event_countdown, 0x13d0u, 98);
    CHK_OWNED(environ, 0x55ccu, 0x44u);
    CHK_OWNED_RELOC(g_heap_free_list, 0xda0u, 100);
    CHK_OWNED(g_dir_data, 0x63b0u, 0x50u);
    CHK_OWNED(g_dir_midi, 0x6400u, 0x50u);
    CHK_OWNED(g_dir_digi, 0x6450u, 0xa0u);
    CHK_OWNED(g_dir_gdv, 0x64f0u, 0x144u);
    CHK_OWNED(g_video_linear_flag, 0x6634u, 0xdcu);
    CHK_OWNED(g_map_list_ptr, 0x6710u, 0x4u);
    CHK_OWNED(g_arg_token_buf, 0x6718u, 0x32u);
    CHK_OWNED(g_player_movement_enabled, 0x674au, 0x13u);
    CHK_OWNED(g_map_menu_marker_selected, 0x675du, 0x1u);
    CHK_OWNED(g_default_message_color, 0x675eu, 0x1u);
    CHK_OWNED(g_map_menu_marker_normal, 0x6765u, 0x1u);
    CHK_OWNED(g_version_string, 0x67c0u, 0x80u);
    CHK_OWNED(g_snapshot_enabled, 0x6840u, 0x1u);
    CHK_OWNED(g_console_input_maxlen, 0x6844u, 0x4u);
    CHK_OWNED(g_console_input_pos, 0x6848u, 0x4u);
    CHK_OWNED(g_console_input_buffer, 0x684cu, 0x4u);
    CHK_OWNED(g_console_input_numeric_only, 0x6854u, 0x1u);
    CHK_OWNED(g_mouse_dx, 0x6870u, 0x4u);
    CHK_OWNED(g_mouse_dy, 0x6874u, 0x4u);
    CHK_OWNED(g_saveunder_sprite_color_ptr, 0x6878u, 0x4u);
    CHK_OWNED(g_cursor_prev_x, 0x6890u, 0x4u);
    CHK_OWNED(g_cursor_prev_y, 0x6894u, 0x4u);
    CHK_OWNED(g_screen_busy_depth, 0xe8c8u, 0x4u);
    CHK_OWNED(g_mouse_relative_mode, 0xe8d0u, 0x1u);
    CHK_OWNED(g_frame_tick_callback, 0xe8d4u, 0x4u);
    CHK_OWNED(g_move_speed_accum, 0xe8d8u, 0x4u);
    CHK_OWNED(g_run_toggle, 0xe8dcu, 0x4u);
    CHK_OWNED(g_run_active, 0xe8e0u, 0x4u);
    CHK(g_saved_int8_offset, 0xe8e4u, 0x4u);
    CHK_OWNED(g_saved_int9_offset, 0xe8e8u, 0x4u);
    CHK(g_saved_int8_segment, 0xe914u, 0x2u);
    CHK_OWNED(g_saved_int9_segment, 0xe916u, 0x2u);
    CHK_OWNED(g_move_input_bits, 0xe920u, 0x2u);
    CHK_OWNED(g_mouse_buttons_held, 0xe928u, 0x1u);
    CHK_OWNED(g_mouse_buttons_prev, 0xe929u, 0x1u);
    CHK_OWNED(g_interaction_cursor_type, 0xe932u, 0x1u);
    CHK_OWNED(g_cursor_primary_action_flag, 0xe938u, 0x1u);
    CHK_OWNED(g_cursor_secondary_action_flag, 0xe939u, 0x1u);
    CHK_OWNED(g_mouse_click_edges, 0xe93au, 0x1u);
    CHK_OWNED(g_cursor_sprite, 0xe950u, 0x900u);
    CHK_OWNED(g_cursor_changed, 0xf250u, 0x1u);
    CHK_OWNED(g_view_grayscale_lut, 0xf254u, 0x100u);
    CHK_OWNED(g_view_grayscale_lut_valid, 0xf354u, 0x1u);
    CHK_OWNED(g_rect_fill_color, 0xf355u, 0x1u);
    CHK_OWNED(g_screen_resolution_index, 0xf358u, 0x12u);
    CHK_OWNED(g_render_mode, 0xf36au, 0x2u);
    CHK_OWNED(g_debug_map_enabled, 0xf36eu, 0x1u);
    CHK_OWNED(g_display_type, 0xf372u, 0x1u);
    CHK_OWNED(g_game_heap_handle, 0xf374u, 0x4u);
    CHK_OWNED(g_audio_sequence_ctx, 0xf444u, 0xcu);
    CHK_OWNED(g_dbase300_chunk_buf, 0xf450u, 0x4u);
    CHK_OWNED(g_audio_sequence_progress, 0xf468u, 0x4u);
    CHK_OWNED(g_current_dbase300_chunk_id, 0xf46cu, 0x8u);
    CHK_OWNED(g_audio_sequence_pending, 0xf474u, 0x4u);
    CHK_OWNED(g_audio_signed_samples, 0xf478u, 0x4u);
    CHK_OWNED(g_sos_digital_device, 0xf4dcu, 0x74u);
    CHK_OWNED(g_sound_enabled, 0xf550u, 0x4u);
    CHK_OWNED(g_dev_mode_flag, 0xf560u, 0x1u);
    CHK_OWNED(g_reloc_base, 0xf56cu, 0x4u);
    CHK_OWNED(g_inventory_dirty_flags, 0xf571u, 0x1u);
    CHK_OWNED(g_cached_dbase200_sprite_handle, 0xf574u, 0x4u);
    CHK_OWNED(g_selected_video_mode, 0xf578u, 0x4u);
    CHK_OWNED(g_dirty_rect_count, 0xf57cu, 0x4u);
    CHK_OWNED(g_dirty_rects, 0xf580u, 0x400u);
    CHK_OWNED(g_prev_dirty_rect_count, 0xf980u, 0x4u);
    CHK_OWNED(g_prev_dirty_rects, 0xf984u, 0x400u);
    CHK_OWNED(g_item_pickup_flags, 0xfd84u, 0x28u);
    CHK_OWNED(g_cursor_interaction_flags, 0xfdacu, 0x10u);
    CHK_OWNED(g_corner_icon_saveunder, 0xfdbcu, 0x4u);
    CHK_OWNED(g_weapon_fire_lock, 0xfdd0u, 0x4u);
    CHK_OWNED(g_pending_weapon_def, 0xfdf4u, 0x4u);
    CHK_OWNED(g_active_weapon_ptr, 0xfe00u, 0x4u);
    CHK_OWNED(g_rng_state2, 0xfe08u, 0x2u);
    CHK_OWNED(g_pending_shot_scale, 0xfe0cu, 0x4u);
    CHK_OWNED(g_pending_fire_aim, 0xfe10u, 0x4u);
    CHK_OWNED(g_map_menu_active, 0xfe28u, 0x4u);
    CHK_OWNED(g_map_menu_count, 0xfe2cu, 0x4u);
    CHK_OWNED(g_map_menu_selected_index, 0xfe30u, 0x4u);
    CHK_OWNED(g_map_menu_selected_entry, 0xfe34u, 0x4u);
    CHK_OWNED(g_help_overlay_enabled, 0xfe38u, 0x70u);
    CHK_OWNED(g_pending_game_action, 0xfea8u, 0x10u);
    CHK_OWNED(g_mouse_button_swap, 0xfeb8u, 0x4u);
    CHK_OWNED(g_inventory_options_request, 0xfebcu, 0x4u);
    CHK_OWNED(g_inspect_popup_active, 0xfec0u, 0x4u);
    CHK_OWNED(g_inventory_panel_open, 0xfec4u, 0x4u);
    CHK_OWNED(g_active_item_hud_icon, 0xfed0u, 0x4u);
    CHK_OWNED(g_current_cursor_entry, 0xfef0u, 0x4u);
    CHK_OWNED(g_cursor_entry_table, 0xfef4u, 0xc00u);
    CHK_OWNED(g_cursor_entry_count, 0x10af4u, 0x8u);
    CHK_OWNED(g_cursor_list_positions, 0x10afcu, 0x14u);
    CHK_OWNED(g_cursor_scroll_offsets, 0x10b10u, 0x14u);
    CHK_OWNED(g_ui_panel_anchor_x, 0x10b24u, 0x4u);
    CHK_OWNED(g_ui_panel_anchor_y, 0x10b28u, 0x8u);
    CHK_OWNED(g_inventory_ui_action, 0x10b30u, 0x4u);
    CHK_OWNED(g_cursor_active_list, 0x10b38u, 0x4u);
    CHK_OWNED(g_inventory_inspect_request, 0x10b3cu, 0x4u);
    CHK_OWNED(g_inspect_popup_layout, 0x10b42u, 0x2eu);
    CHK_OWNED(g_inventory_active_tab, 0x10b70u, 0x54u);
    CHK(g_inventory_hotspot_list, 0x10bc4u, 0x68u);
    CHK_OWNED(g_inventory_count, 0x10c2cu, 0x4u);
    CHK_OWNED(g_inventory_slots, 0x10c30u, 0x400u);
    CHK_OWNED(g_left_hand_item, 0x11030u, 0x4u);
    CHK_OWNED(g_displayed_item_left, 0x11034u, 0x4u);
    CHK_OWNED(g_selected_item_secondary, 0x11038u, 0x4u);
    CHK_OWNED(g_right_hand_item, 0x1103cu, 0x4u);
    CHK_OWNED(g_displayed_item_right, 0x11040u, 0x4u);
    CHK_OWNED(g_selected_item_primary, 0x11044u, 0x4u);
    CHK_OWNED(g_inspect_popup_state, 0x110c0u, 0x4u);
    CHK_OWNED(g_inspect_page_count, 0x110fcu, 0x4u);
    CHK_OWNED(g_inspect_current_page, 0x11184u, 0x4u);
    CHK_OWNED(g_inspect_info_available, 0x11188u, 0x4u);
    CHK_OWNED(g_inventory_arrow_state, 0x111a0u, 0xcu);
    CHK_OWNED(g_ui_panel_scratch_handle, 0x111acu, 0x8u);
    CHK_OWNED(g_active_weapon_attrs, 0x111b4u, 0x30u);
    CHK_OWNED(g_active_weapon_ammo_id, 0x111e4u, 0x118u);
    CHK_OWNED(g_inventory_synthetic_primary, 0x112fcu, 0x4u);
    CHK_OWNED(g_pending_choice_accept_index, 0x11304u, 0x4u);
    CHK_OWNED(g_held_item_icon_spans, 0x11310u, 0x6a4u);
    CHK_OWNED(g_held_item_icon_width, 0x119b4u, 0x4u);
    CHK_OWNED(g_held_item_slide_timer, 0x119bcu, 0x4u);
    CHK_OWNED(g_player_locomotion_flags, 0x119c0u, 0x1u);
    CHK_OWNED(g_player_airborne, 0x119c1u, 0x4u);
    CHK_OWNED(g_entity_def_cache_head, 0x119d8u, 0x4u);
    CHK_OWNED(g_entity_def_cache_nodes, 0x119dcu, 0x438u);
    CHK_OWNED(g_entity_def_cache_count, 0x11e14u, 0x4u);
    CHK_OWNED(g_dbase100_base, 0x11e1cu, 0x4u);
    CHK_OWNED(g_dbase100_inventory_table, 0x11e20u, 0x4u);
    CHK_OWNED(g_dbase100_dialogue_table, 0x11e24u, 0x4u);
    CHK_OWNED(g_dbase100_record_bitmap, 0x11e28u, 0x4u);
    CHK_OWNED(g_value_reduction_factor, 0x11e30u, 0x4u);
    CHK_OWNED(g_object_select_easy_flag, 0x11e34u, 0xau);
    CHK_OWNED(g_dialogue_action_queue_count, 0x11e3eu, 0x4u);
    CHK_OWNED(g_dialogue_action_queue, 0x11e42u, 0x60u);
    CHK_OWNED(g_dbase100_choice_cursor, 0x11ea2u, 0x4u);
    CHK_OWNED(g_dbase100_choice_remaining, 0x11ea6u, 0x4u);
    CHK_OWNED(g_dbase100_choice_mode, 0x11eaau, 0x4u);
    CHK_OWNED(g_dbase100_choice_count, 0x11eaeu, 0x4u);
    CHK_OWNED(g_dbase100_pending_topic, 0x11eb2u, 0x4u);
    CHK_OWNED(g_dbase100_choice_record_indices, 0x11eb6u, 0x4cu);
    CHK_OWNED(g_object_template_flags, 0x11f02u, 0x4u);
    CHK_OWNED(g_dbase200_filename, 0x11f06u, 0x80u);
    CHK_OWNED(g_dbase300_filename, 0x11f86u, 0x80u);
    CHK_OWNED(g_cutscenes_seen_count, 0x12006u, 0x6u);
    CHK_OWNED(g_voice_stream_state, 0x1200cu, 0x4u);
    CHK_OWNED(g_voice_file_handle, 0x12010u, 0x4u);
    CHK_OWNED(g_voice_stop_handle, 0x12014u, 0x4u);
    CHK_OWNED(g_voice_bytes_remaining, 0x12018u, 0x4u);
    CHK_OWNED(g_voice_is_dpcm, 0x12034u, 0x4u);
    CHK_OWNED(g_voice_dpcm_predictor, 0x12038u, 0x4u);
    CHK_OWNED(g_timed_message_color, 0x12040u, 0x1u);
    CHK_OWNED(g_voice_sample_rate, 0x12041u, 0x4u);
    CHK_OWNED(g_voice_refill_pending, 0x120b9u, 0x4u);
    CHK_OWNED(g_message_cache_head, 0x120c1u, 0x404u);
    CHK_OWNED(g_dialogue_script_handle, 0x124c5u, 0x4u);
    CHK_OWNED(g_timed_message_lines, 0x124c9u, 0x118u);
    CHK_OWNED(g_timed_message_text_buffer, 0x125e1u, 0x200u);
    CHK_OWNED(g_timed_message_line_count, 0x127e1u, 0x4u);
    CHK_OWNED(g_timed_message_timer, 0x127e5u, 0x4u);
    CHK_OWNED(g_dialogue_segments, 0x127fdu, 0xcu);
    CHK_OWNED(g_dialogue_timer_rate, 0x12809u, 0x4u);
    CHK_OWNED(g_active_dialogue_context, 0x13115u, 0x4u);
    CHK_OWNED(g_dialogue_line_dwell, 0x13119u, 0x4u);
    CHK_OWNED(g_dialogue_dwell_divisor, 0x1311du, 0x4u);
    CHK_OWNED(g_dialogue_segment_index, 0x13121u, 0x4u);
    CHK_OWNED(g_move_freeze_gate, 0x13125u, 0x4u);
    CHK_OWNED(g_dialogue_reveal_ramp, 0x13129u, 0x4u);
    CHK_OWNED(g_choice_option_records, 0x13149u, 0x40u);
    CHK_OWNED(g_choice_line_records, 0x13189u, 0x140u);
    CHK_OWNED(g_choice_text_buffer, 0x132c9u, 0x800u);
    CHK_OWNED(g_choice_line_count, 0x13ac9u, 0x4u);
    CHK_OWNED(g_choice_interaction_mode, 0x13acdu, 0x4u);
    CHK_OWNED(g_choice_reveal_ramp, 0x13ae5u, 0x4u);
    CHK_OWNED(g_dialogue_busy_flag, 0x13aeau, 0x4u);
    CHK_OWNED(g_cutscene_overlay_active, 0x13c70u, 0x4u);
    CHK_OWNED(g_cutscene_image_handle, 0x13c74u, 0x4u);
    CHK_OWNED(g_screen_backup_handle, 0x13d18u, 0x4u);
    CHK_OWNED(g_saved_movement_enabled, 0x13d24u, 0x4u);
    CHK_OWNED(g_message_resource_handle, 0x13d28u, 0x4u);
    CHK_OWNED(g_hud_weapon_das_handle, 0x13d6cu, 0x4u);
    CHK_OWNED(g_hud_panel_das_handle0, 0x13d74u, 0x4u);
    CHK_OWNED(g_hud_panel_das_handle1, 0x13d78u, 0x4u);
    CHK_OWNED(g_weapon_hud_anim_table, 0x13d84u, 0x80u);
    CHK_OWNED(g_weapon_hud_anim_count, 0x13e04u, 0x4u);
    CHK_OWNED(g_weapon_hud_anim_accum, 0x13e08u, 0x4u);
    CHK_OWNED(g_active_weapon_ammo, 0x13e6cu, 0x4u);
    CHK_OWNED(g_active_weapon_item_id, 0x13e70u, 0x4u);
    CHK_OWNED(g_active_weapon_ammo_cap, 0x13e74u, 0x20u);
    CHK_OWNED(g_voice_decode_suspended, 0x13e94u, 0x4u);
    CHK_OWNED(g_menu_frontend_flag, 0x13ea0u, 0x4u);
    CHK_OWNED(g_playback_menu_scroll_anchor, 0x13ea4u, 0x4u);
    CHK_OWNED(g_entity_sound_emitter, 0x13eb0u, 0x24u);
    CHK_OWNED(g_active_sound_handles, 0x13ed4u, 0x9a0u);
    CHK_OWNED(g_sound_voice_descriptors, 0x14874u, 0x80u);
    CHK_OWNED(g_sound_sample_table, 0x148f4u, 0x4u);
    CHK_OWNED(g_sound_bank_file_handle, 0x148f8u, 0x4u);
    CHK_OWNED(g_sound_sample_count, 0x148fcu, 0x4u);
    CHK_OWNED(g_voice_sos_callback, 0x14900u, 0x4u);
    CHK_OWNED(g_pending_sound_param, 0x14906u, 0x1u);
    CHK_OWNED(g_format_flags, 0x1491du, 0x1u);
    CHK_OWNED(g_current_decoded_frame, 0x14944u, 0x1u);
    CHK_OWNED(g_view_floor_clearance, 0x1497cu, 0x4u);
    CHK_OWNED(g_render_source_base_ptr, 0x14980u, 0x4u);
    CHK_OWNED(g_door_worklist, 0x1498cu, 0x4u);
    CHK_OWNED(g_current_proc_tag, 0x1499cu, 0x4u);
    CHK_OWNED(g_secondary_surface_list, 0x14b18u, 0x400u);
    CHK(g_world_span_record, 0x14f18u, 0x16u);
    CHK_OWNED(g_span_fill_mode_word, 0x14f2eu, 0x2u);
    CHK_OWNED(g_visible_extent_count, 0x15220u, 0x4u);
    CHK_OWNED(g_visible_extent_list, 0x15224u, 0x40u);
    CHK_OWNED(g_view_clip_plane, 0x15264u, 0x4u);
    CHK_OWNED(g_view_bounds_rect, 0x1526cu, 0x4u);
    CHK_OWNED(g_view_params_block, 0x15270u, 0x4u);
    CHK_OWNED(g_perspective_scale, 0x15288u, 0x4u);
    CHK_OWNED(g_map_geometry_selector, 0x15294u, 0x2u);
    CHK_OWNED(g_world_span_bottom, 0x152b4u, 0x2u);
    CHK_OWNED(g_world_span_top, 0x152b6u, 0x2u);
    CHK_OWNED(g_face_span_bottom, 0x152b8u, 0x2u);
    CHK_OWNED(g_face_span_top, 0x152bau, 0x2u);
    CHK_OWNED(g_span_gouraud_colour_a, 0x152c2u, 0x2u);
    CHK_OWNED(g_span_gouraud_colour_b, 0x152c4u, 0x2u);
    CHK_OWNED(g_surface_record_selector, 0x152c8u, 0x2u);
    CHK_OWNED(g_vertex_selector, 0x152ccu, 0x2u);
    CHK_OWNED(g_sector_cull_coord, 0x152fau, 0x2u);
    CHK_OWNED(g_camera_sin, 0x15310u, 0x2u);
    CHK_OWNED(g_camera_cos, 0x15312u, 0x2u);
    CHK_OWNED(g_secondary_surface_count, 0x15318u, 0x2u);
    CHK_OWNED(g_last_frame_tick, 0x15320u, 0x2u);
    CHK_OWNED(g_frame_time_scale, 0x15324u, 0x6u);
    CHK_OWNED(g_anim_clock, 0x1532au, 0x2u);
    CHK_OWNED(g_reflection_view_count, 0x15340u, 0x4u);
    CHK(g_reflection_view_list, 0x15344u, 0x8cu);
    CHK_OWNED(g_has_secondary_surfaces, 0x153d0u, 0x1u);
    CHK_OWNED(g_secondary_subpass_flags, 0x153d2u, 0x1u);
    CHK_OWNED(g_render_sector_walk_mode, 0x153d3u, 0x1u);
    CHK_OWNED(g_secondary_subpass_id, 0x153f9u, 0x1u);
    CHK_OWNED(g_das_eviction_protected_allocation, 0x15400u, 0x4u);
    CHK_OWNED(g_das_render_scale, 0x15404u, 0x4u);
    CHK_OWNED(g_render_target_buffer, 0x15414u, 0x4u);
    CHK(g_map_buffer_pitch, 0x15438u, 0x4u);
    CHK(g_map_buffer_base, 0x1543cu, 0x4u);
    CHK(g_map_scale_x, 0x15440u, 0x4u);
    CHK(g_map_scale_y, 0x15444u, 0x14u);
    CHK(g_map_draw_color, 0x15458u, 0x2u);
    CHK(g_map_world_center_x, 0x1545au, 0x2u);
    CHK(g_map_world_center_y, 0x1545cu, 0x2u);
    CHK(g_map_screen_center_y, 0x1545eu, 0x2u);
    CHK(g_map_screen_center_x, 0x15460u, 0x18u);
    CHK_OWNED(g_framebuffer_bytes, 0x15478u, 0x4u);
    CHK_OWNED(g_warp_dest_a, 0x1547cu, 0x4u);
    CHK_OWNED(g_warp_dest_b, 0x15480u, 0x4u);
    CHK_OWNED(g_map_first_load_flag, 0x15484u, 0x4u);
    CHK_OWNED(g_palette_rgb_ptr, 0x15488u, 0x4u);
    CHK_OWNED(g_audio_decode_buffer_a, 0x1548cu, 0x4u);
    CHK_OWNED(g_audio_decode_buffer_b, 0x15490u, 0x4u);
    CHK_OWNED(g_audio_silence_buffer, 0x15494u, 0x4u);
    CHK_OWNED(g_screen_pitch, 0x15498u, 0x8u);
    CHK_OWNED(g_screen_height, 0x154a0u, 0x8u);
    CHK_OWNED(g_scanline_dest_offset_table, 0x154a8u, 0x780u);
    CHK_OWNED(g_object_buffer_free, 0x15c28u, 0x4u);
    CHK_OWNED(g_object_table_header, 0x15c30u, 0x4u);
    CHK_OWNED(g_das_cache_heap_handle, 0x15c3cu, 0x4u);
    CHK_OWNED(g_resource_pool, 0x15c40u, 0x4u);
    CHK_OWNED(g_sfx_nodes, 0x15c44u, 0x4u);
    CHK_OWNED(g_das_collision_buffer, 0x15c50u, 0x4u);
    CHK_OWNED(g_view_w, 0x15cd8u, 0x4u);
    CHK_OWNED(g_view_h, 0x15cdcu, 0x4u);
    CHK_OWNED(g_view_x, 0x15ce0u, 0x4u);
    CHK_OWNED(g_view_y, 0x15ce4u, 0x4u);
    CHK_OWNED(g_map_das_dir_table_buffer, 0x15ce8u, 0x4u);
    CHK_OWNED(g_ademo_das_fat_buffer, 0x15cf0u, 0x4u);
    CHK_OWNED(g_das_file_handle, 0x15d00u, 0x4u);
    CHK_OWNED(g_das_remap_chunk_10000_ptr, 0x15d08u, 0x4u);
    CHK(g_das_remap_chunk_100_a_ptr, 0x15d10u, 0x4u);
    CHK_OWNED(g_texture_flat_color_table, 0x15d14u, 0x1000u);
    CHK_OWNED(g_das_remap_chunk_4000_ptr, 0x16d14u, 0x4u);
    CHK_OWNED(g_world_glow_table_ptr, 0x16d18u, 0x4u);
    CHK_OWNED(g_world_tint_table_ptr, 0x16d1cu, 0x4u);
    CHK(g_das_remap_chunk_100_b_ptr, 0x16d20u, 0x8u);
    CHK_OWNED(g_world_shading_table_ptr, 0x16d28u, 0x8u);
    CHK_OWNED(g_das_entry_status_table, 0x16d30u, 0x2c00u);
    CHK_OWNED(g_das_cache_slots, 0x19930u, 0x5dcu);
    CHK_OWNED(g_roth_error_code, 0x19f0cu, 0x4u);
    CHK_OWNED(g_das_palette_remap_prefix, 0x19f10u, 0x2u);
    CHK_OWNED(g_gamma_level, 0x19f12u, 0x16u);
    CHK_OWNED(g_render_target_selector_secondary, 0x19f28u, 0x2u);
    CHK_OWNED(g_render_target_secondary_height, 0x19f2au, 0x2u);
    CHK_OWNED(g_render_target_secondary_size, 0x19f2cu, 0x4u);
    CHK_OWNED(g_das_special_fat_index, 0x19f34u, 0x4u);
    CHK_OWNED(g_render_active, 0x19f38u, 0x1u);
    CHK_OWNED(g_framebuffer_from_dos_block, 0x19f3au, 0x1u);
    CHK_OWNED(g_damage_flash_level, 0x19f3bu, 0x4u);
    CHK_OWNED(g_das_skip_palette_load_flag, 0x19f3fu, 0x1u);
    CHK_OWNED(g_resource_pool_small_flag, 0x19f41u, 0x1u);
    CHK_OWNED(g_player_speed_reduction_request, 0x19f54u, 0x4u);
    CHK_OWNED(g_player_speed_reduction_shift, 0x19f58u, 0x4u);
    CHK_OWNED(g_state_record_list_count, 0x19f5cu, 0x4u);
    CHK_OWNED(g_item_autoselected_flag, 0x19f60u, 0x4u);
    CHK_OWNED(g_if_item_list_count, 0x19f64u, 0x4u);
    CHK(g_if_item_list, 0x19f68u, 0x40u);
    CHK_OWNED(g_last_item_record, 0x19fa8u, 0x4u);
    CHK_OWNED(g_item_drop_position, 0x19facu, 0x12cu);
    CHK_OWNED(g_object_ptr_array, 0x1a0d8u, 0x4u);
    CHK_OWNED(g_pending_command_record, 0x1a0dcu, 0x4u);
    CHK_OWNED(g_state_link_obj_ptr, 0x1a0e4u, 0x4u);
    CHK_OWNED(g_state_link_word_a, 0x1a0e8u, 0x4u);
    CHK_OWNED(g_state_link_word_b, 0x1a0ecu, 0x4u);
    CHK_OWNED(g_player_health, 0x1a0f0u, 0x4u);
    CHK_OWNED(g_active_object, 0x1a0f8u, 0x4u);
    CHK_OWNED(g_command_source_object, 0x1a100u, 0x4u);
    CHK_OWNED(g_anim_step_mode, 0x1a104u, 0x4u);
    CHK_OWNED(g_active_effect_pool, 0x1a118u, 0x4u);
    CHK_OWNED(g_effect_list_b, 0x1a11cu, 0x4u);
    CHK_OWNED(g_damage_emitter_ptr, 0x1a120u, 0x4u);
    CHK_OWNED(g_player_move_delta_x, 0x1a124u, 0x4u);
    CHK_OWNED(g_player_move_delta_y, 0x1a128u, 0x4u);
    CHK_OWNED(g_player_move_delta_z, 0x1a12cu, 0x10u);
    CHK_OWNED(g_state_link_buf_ptr, 0x1a13cu, 0x4u);
    CHK_OWNED(g_command_chain_interrupt, 0x1a268u, 0x1u);
    CHK_OWNED(g_block_list_head, 0x1a270u, 0x4u);
    CHK_OWNED(g_pool_check_enabled, 0x1a278u, 0x4u);
    CHK_OWNED(g_active_world_remap_selector, 0x1a2a8u, 0x2u);
    CHK_OWNED(g_active_world_remap_base, 0x1a2acu, 0x4u);
    CHK_OWNED(g_world_span_fn, 0x1a2bcu, 0x4u);
    CHK_OWNED(g_world_span_fn2, 0x1a2c0u, 0x4u);
    CHK_OWNED(g_world_span_fn_alt, 0x1a2c4u, 0x4u);
    CHK_OWNED(g_world_span_fn_alt2, 0x1a2c8u, 0x4u);
    CHK_OWNED(g_span_endpoint_a, 0x1a2ccu, 0x4u);
    CHK_OWNED(g_span_endpoint_a_colstep, 0x1a2d0u, 0x4u);
    CHK_OWNED(g_span_endpoint_b, 0x1a2d4u, 0x4u);
    CHK_OWNED(g_span_endpoint_b_colstep, 0x1a2d8u, 0x4u);
    CHK_OWNED(g_span_accum_init, 0x1a2dcu, 0x1u);
    CHK_OWNED(g_span_shade_seed, 0x1a2ddu, 0x1u);
    CHK(g_span_pixel_step, 0x1a2e0u, 0x4u);
    CHK_OWNED(g_span_eax_step_lo, 0x1a2e2u, 0x1u);
    CHK_OWNED(g_wall_vstep, 0x1a2e4u, 0x4u);
    CHK_OWNED(g_span_texU_accum, 0x1a2ecu, 0x4u);
    CHK_OWNED(g_span_texV_accum, 0x1a2f0u, 0x4u);
    CHK_OWNED(g_render_double_scanline_flag, 0x1a310u, 0x1u);
    CHK_OWNED(g_span_round_half, 0x1a316u, 0x2u);
    CHK_OWNED(g_wall_render_flags, 0x1a334u, 0x2u);
    CHK_OWNED(g_wall_segment_width, 0x1a336u, 0x2u);
    CHK_OWNED(g_span_src_wrap_base, 0x1a338u, 0x4u);
    CHK_OWNED(g_span_eax_accum_init, 0x1a344u, 0x4u);
    CHK_OWNED(g_wall_column_count, 0x1a348u, 0x2u);
    CHK_OWNED(g_span_draw_mode_flags, 0x1a34cu, 0x1u);
    CHK_OWNED(g_span_textured_mode_flag, 0x1a352u, 0x1u);
    CHK_OWNED(g_span_blend_mode_flag, 0x1a354u, 0x1u);
    CHK_OWNED(g_render_x_flip_flag, 0x1a356u, 0x1u);
    CHK_OWNED(g_sprite_span_remaining, 0x1a358u, 0x4u);
    CHK_OWNED(g_sprite_perspective_step, 0x1a35cu, 0x4u);
    CHK_OWNED(g_sprite_tex_step_frac, 0x1a360u, 0x4u);
    CHK_OWNED(g_sprite_column_fn, 0x1a368u, 0x4u);
    CHK_OWNED(g_current_span_record, 0x1a36cu, 0x4u);
    CHK(g_sprite_column_loop_guard, 0x1a370u, 0x4u);
    CHK_OWNED(g_sprite_span_width, 0x1a372u, 0x2u);
    CHK_OWNED(g_sprite_src_coord, 0x1a374u, 0x4u);
    CHK_OWNED(g_sprite_src_coord_step, 0x1a378u, 0x4u);
    CHK_OWNED(g_sprite_tex_step_u, 0x1a38cu, 0x4u);
    CHK_OWNED(g_sprite_tex_step_u2, 0x1a390u, 0x4u);
    CHK_OWNED(g_sprite_tex_step_v, 0x1a394u, 0x4u);
    CHK_OWNED(g_sprite_tex_step_v2, 0x1a398u, 0x4u);
    CHK_OWNED(g_sprite_span_flip, 0x1a3acu, 0xeu);
    CHK_OWNED(g_sprite_span_shade, 0x1a3bau, 0x1u);
    CHK_OWNED(g_floorceil_span_fn, 0x1a3c0u, 0x4u);
    CHK_OWNED(g_floorceil_span_fn_alt, 0x1a3c4u, 0x4u);
    CHK_OWNED(g_clip_output_vertex_count, 0x1a3ccu, 0x4u);
    CHK_OWNED(g_floorceil_accum_a, 0x1a3dcu, 0x4u);
    CHK_OWNED(g_floorceil_accum_b, 0x1a3e0u, 0x14u);
    CHK_OWNED(g_floorceil_step_a, 0x1a3f4u, 0x4u);
    CHK_OWNED(g_floorceil_step_b, 0x1a3f8u, 0x4u);
    CHK_OWNED(g_floorceil_clip_flags, 0x1a434u, 0x2u);
    CHK_OWNED(g_clip_boundary, 0x1a436u, 0x2u);
    CHK_OWNED(g_floorceil_edge_orientation, 0x1a43au, 0x2u);
    CHK_OWNED(g_floorceil_edge_x_end, 0x1a43cu, 0x2u);
    CHK_OWNED(g_floorceil_edge_x_start, 0x1a43eu, 0x2u);
    CHK_OWNED(g_floorceil_edge_emitted, 0x1a440u, 0x2u);
    CHK_OWNED(g_atan_table, 0x1aa46u, 0x2u);
    CHK(g_sprite_node_pool, 0x1aad0u, 0x870u);
    CHK_OWNED(g_sprite_render_queue_head, 0x1b340u, 0x4u);
    CHK_OWNED(g_snapshot_work_buf, 0x1b35cu, 0x4u);
    CHK_OWNED(g_snapshot_filename_buf, 0x1b370u, 0x84u);
    CHK_OWNED(g_door_count, 0x1b3f4u, 0x1u);
    CHK_OWNED(g_door_pool, 0x1b3f8u, 0x2u);
    CHK(g_door_state_table, 0x1b3fau, 0xbc2u);
    CHK_OWNED(g_secondary_door_count, 0x1bfbcu, 0x1u);
    CHK_OWNED(g_secondary_door_pool, 0x1bfc0u, 0x118u);
    CHK_OWNED(g_collision_move_entity_geom, 0x1c0d8u, 0x4u);
    CHK_OWNED(g_collision_move_entity, 0x1c0dcu, 0x4u);
    CHK_OWNED(g_collision_target_radius, 0x1c0ecu, 0x4u);
    CHK_OWNED(g_collision_target_active, 0x1c0f0u, 0x4u);
    CHK_OWNED(g_collision_hit_entity, 0x1c0f4u, 0x4u);
    CHK_OWNED(g_view_pitch_applied, 0x1c108u, 0x8u);
    CHK_OWNED(g_player_height, 0x1c110u, 0x2u);
    CHK_OWNED(g_locate_query_x, 0x1c120u, 0x4u);
    CHK_OWNED(g_locate_query_z, 0x1c124u, 0x4u);
    CHK_OWNED(g_locate_query_y, 0x1c128u, 0x4u);
    CHK_OWNED(g_collision_entity_count, 0x1c12cu, 0x4u);
    CHK_OWNED(g_collision_box_max, 0x1c130u, 0x4u);
    CHK_OWNED(g_collision_box_min, 0x1c134u, 0x4u);
    CHK_OWNED(g_collision_radius_sq, 0x1c138u, 0x4u);
    CHK_OWNED(g_collision_corner_radius_sq, 0x1c140u, 0x4u);
    CHK_OWNED(g_collision_radius, 0x1c144u, 0x4u);
    CHK_OWNED(g_max_climb, 0x1c148u, 0x2u);
    CHK_OWNED(g_collision_blocker_object, 0x1c16cu, 0x4u);
    CHK_OWNED(g_collision_portal_continue, 0x1c190u, 0x2u);
    CHK_OWNED(g_collision_sector_stack_count, 0x1c192u, 0x2u);
    CHK_OWNED(g_collision_sector_stack, 0x1c194u, 0x42u);
    CHK_OWNED(g_player_sector_cache, 0x1c1d6u, 0x2u);
    CHK_OWNED(g_viewmodel_shade_level, 0x1c1deu, 0x1u);
    CHK_OWNED(g_collision_hit_flags, 0x1c1e0u, 0x1u);
    CHK_OWNED(g_collision_step_active, 0x1c1e2u, 0x1u);
    CHK_OWNED(g_collision_edge_ax, 0x1c1efu, 0x2u);
    CHK_OWNED(g_collision_edge_ay, 0x1c1f1u, 0x2u);
    CHK_OWNED(g_collision_edge_bx, 0x1c1f3u, 0x2u);
    CHK_OWNED(g_collision_edge_by, 0x1c1f5u, 0x2u);
    CHK_OWNED(g_dos_transfer_buffer_linear, 0x1c1f8u, 0x4u);
    CHK_OWNED(g_dos_transfer_buffer_selector, 0x1c1fcu, 0x2u);
    CHK_OWNED(g_projection_build_dir, 0x1c200u, 0x4u);
    CHK(g_projection_table_backup, 0x1c204u, 0x280u);
    CHK_OWNED(g_render_column_source_table, 0x1c484u, 0x1u);
    CHK_OWNED(g_current_das_fat_entry, 0x1c70cu, 0x4u);
    CHK_OWNED(g_current_das_block_size_bytes, 0x1c72cu, 0x4u);
    CHK_OWNED(g_current_das_fat_index_x2, 0x1c730u, 0x4u);
    CHK(g_current_das_cache_slot, 0x1c734u, 0x4u);
    CHK(g_current_das_block_allocation, 0x1c738u, 0x4u);
    CHK(g_current_das_alloc_size, 0x1c73cu, 0x4u);
    CHK_OWNED(g_das_low_index_bitset, 0x1c740u, 0x200u);
    CHK_OWNED(g_current_das_cache_slot_index, 0x1c940u, 0x2u);
    CHK_OWNED(g_das_special_index_load_flag, 0x1c942u, 0x1u);
    CHK_OWNED(g_floorceil_vertex_count, 0x1c944u, 0x2u);
    CHK(g_floorceil_vertex_records, 0x1c946u, 0x3c6u);
    CHK_OWNED(g_floorceil_span_records, 0x1cd0cu, 0x3c30u);
    CHK_OWNED(g_world_surface_draw_flags, 0x2093cu, 0xcu);
    CHK_OWNED(g_wall_proj_y0, 0x20948u, 0x2u);
    CHK_OWNED(g_wall_proj_y1, 0x2094au, 0x2u);
    CHK_OWNED(g_wall_proj_y2, 0x2094cu, 0x2u);
    CHK_OWNED(g_wall_proj_y3, 0x2094eu, 0x2u);
    CHK_OWNED(g_view_bound_right, 0x20968u, 0x2u);
    CHK_OWNED(g_view_bound_left, 0x2096au, 0x2u);
    CHK_OWNED(g_view_bound_bottom, 0x2096cu, 0x2u);
    CHK_OWNED(g_view_bound_top, 0x2096eu, 0x2u);
    CHK_OWNED(g_column_clip_mode, 0x20970u, 0x1u);
    CHK_OWNED(g_span_src_row_width, 0x20978u, 0x4u);
    CHK_OWNED(g_span_src_wrap_reoffset, 0x2097cu, 0x32u);
    CHK_OWNED(g_world_alt_render_flags, 0x209aeu, 0x2u);
    CHK_OWNED(g_floor_tex_caps, 0x209b2u, 0x2u);
    CHK_OWNED(g_sprite_view_angle, 0x209f8u, 0x2u);
    CHK_OWNED(g_view_offset_x, 0x20a04u, 0x2u);
    CHK_OWNED(g_view_offset_y, 0x20a06u, 0x2u);
    CHK_OWNED(g_floorceil_depth_clip_bias, 0x20a1eu, 0x2u);
    CHK_OWNED(g_floorceil_clip_scale, 0x20a20u, 0x2u);
    CHK_OWNED(g_render_textured_flag, 0x20a22u, 0x2u);
    CHK_OWNED(g_sprite_fill_index, 0x20a24u, 0x4u);
    CHK_OWNED(g_span_clip_source, 0x20a28u, 0x1u);
    CHK_OWNED(g_parallax_sky_active, 0x20a2au, 0x1u);
    CHK_OWNED(g_world_span_colorkey, 0x20a2cu, 0x2u);
    CHK_OWNED(g_current_surface_render_flags, 0x20a2eu, 0x2u);
    CHK_OWNED(g_sprite_render_mode, 0x20a30u, 0x1u);
    CHK_OWNED(g_span_callback, 0x20a34u, 0x4u);
    CHK_OWNED(g_map_das_fat_buffer, 0x20a38u, 0x4u);
    CHK_OWNED(g_world_render_subpass_kind, 0x20a48u, 0x8u);
    CHK_OWNED(g_subpass_surfrec_ref, 0x20a50u, 0xau);
    CHK_OWNED(g_subpass_reflect_param_a, 0x20a5au, 0x2u);
    CHK_OWNED(g_subpass_reflect_param_b, 0x20a5cu, 0x2u);
    CHK_OWNED(g_subpass_persp_step, 0x20a68u, 0x4u);
    CHK_OWNED(g_view_center_x, 0x20a70u, 0x2u);
    CHK_OWNED(g_view_center_y, 0x20a72u, 0x2u);
    CHK_OWNED(g_view_pitch, 0x20a74u, 0x4u);
    CHK_OWNED(g_current_das_entry_id, 0x20a78u, 0x8u);
    CHK_OWNED(g_player_vel_accum_x, 0x20a80u, 0x4u);
    CHK_OWNED(g_player_vel_accum_y, 0x20a84u, 0x4u);
    CHK_OWNED(g_player_angle, 0x20a8au, 0x2u);
    CHK_OWNED(g_player_x, 0x20a8eu, 0x2u);
    CHK_OWNED(g_player_z, 0x20a92u, 0x2u);
    CHK_OWNED(g_player_y, 0x20a96u, 0x2u);
    CHK_OWNED(g_framebuffer_ptr, 0x20a98u, 0x4u);
    CHK_OWNED(g_image_surface, 0x20a9cu, 0x4u);
    CHK_OWNED(g_map_objects_buffer, 0x20aa4u, 0x4u);
    CHK_OWNED(g_map_geometry_buffer, 0x20aa8u, 0x4u);
    CHK_OWNED(g_sector_geom_base, 0x20aacu, 0x4u);
    CHK_OWNED(g_collision_restore_x, 0x20ab4u, 0x4u);
    CHK_OWNED(g_collision_restore_y, 0x20ab8u, 0x4u);
    CHK_OWNED(g_vel_queue_a, 0x20abeu, 0x2u);
    CHK_OWNED(g_vel_queue_b, 0x20b42u, 0x2u);
    CHK_OWNED(g_frame_tick_counter, 0x20bccu, 0x2u);
    CHK_OWNED(g_view_scale_flags, 0x20bd4u, 0x1u);
    CHK_OWNED(g_vel_queue_select, 0x20bd6u, 0x2u);
    CHK_OWNED(g_turn_accum, 0x20bd8u, 0x2u);
    CHK_OWNED(g_player_move_rate_counter, 0x20bdau, 0x2u);
    CHK_OWNED(g_max_step_height, 0x20bdeu, 0x2u);
    CHK_OWNED(g_min_fit, 0x20be0u, 0x2u);
    CHK_OWNED(g_transparency_blend_selector, 0x20be2u, 0x2u);
    CHK_OWNED(g_vga_mode_configured, 0x20be4u, 0x2u);
    CHK_OWNED(g_video_mode_flags, 0x20be6u, 0x2u);
    CHK_OWNED(g_geometry_selector, 0x20be8u, 0x2u);
    CHK_OWNED(g_render_width, 0x20bf2u, 0x2u);
    CHK_OWNED(g_render_viewport_height, 0x20bf4u, 0x2u);
    CHK_OWNED(g_render_height, 0x20bf6u, 0x2u);
    CHK_OWNED(g_blur_flag, 0x20bf8u, 0x2u);
    CHK(g_antialias_mode, 0x20bfau, 0x2u);
    CHK_OWNED(g_render_viewport_reconfig, 0x20bfcu, 0x2u);
    CHK_OWNED(g_subpass_patch_gate, 0x20bfeu, 0x2u);
    CHK_OWNED(g_flush_predraw_flag, 0x20c04u, 0x2u);
    CHK_OWNED(g_render_target_selector, 0x20c06u, 0x2u);
    CHK_OWNED(g_rawscreen_flag, 0x20c08u, 0x1u);
    CHK_OWNED(g_das_cache_tick, 0x20c0au, 0x2u);
    CHK_OWNED(g_viewport_top_margin, 0x20c0cu, 0x2u);
    CHK_OWNED(g_text_color_ramp_selector, 0x20c0eu, 0x4u);
    CHK_OWNED(g_player_sector, 0x20c12u, 0x2u);
    CHK_OWNED(g_render_shade_level, 0x20c1au, 0x2u);
    CHK_OWNED(g_key_state_bitmap, 0x20c3cu, 0x1u);
    CHK_OWNED(g_key_modifier_flags, 0x20c42u, 0x1u);
    CHK_OWNED(g_hires_line_doubling_flag, 0x20cbdu, 0x1u);
    CHK_OWNED(g_das_unk_0x22, 0x20cbeu, 0x2u);
    CHK_OWNED(g_turn_view_scale_state, 0x20cc0u, 0x1u);
    CHK_OWNED(g_flat_shading_flag, 0x20cc4u, 0x1u);
    CHK_OWNED(g_dta_initialized, 0x20f48u, 0x4u);
    CHK_OWNED(g_dos_dta, 0x20f4cu, 0x1eu);
    CHK_OWNED(g_dos_dta_name, 0x20f6au, 0x72u);
    CHK_OWNED(g_projectile_collision_width, 0x20fdcu, 0x4u);
    CHK_OWNED(g_dynamic_entity_count, 0x20fe0u, 0x4u);
    CHK_OWNED(g_dynamic_entity_table, 0x20fe4u, 0x1e1u);
    CHK_OWNED(g_object_table_dirty, 0x211c5u, 0x1u);
    CHK_OWNED(g_object_table_generation, 0x211c7u, 0x4u);
    CHK_OWNED(g_spawn_projectile_is_player, 0x211cbu, 0x1u);
    CHK_OWNED(g_saved_int24_vector, 0x211d0u, 0x4u);
    CHK_OWNED(g_sfx_query_capacity, 0x211dcu, 0x4u);
    CHK_OWNED(g_sfx_query_result_count, 0x211e0u, 0x4u);
    CHK_OWNED(g_particle_pool, 0x21864u, 0x4u);
    CHK_OWNED(g_dpcm_step_table, 0x218a4u, 0x45cu);
    CHK_OWNED(g_gdv_user_callback, 0x21d00u, 0x4u);
    CHK_OWNED(g_gdv_stream_flags, 0x21d0cu, 0x4u);
    CHK_OWNED(g_gdv_context, 0x21d14u, 0x4u);
    CHK_OWNED(g_gdv_audio_buf_size, 0x21d2cu, 0x4u);
    CHK_OWNED(g_gdv_decode_buffer, 0x21d34u, 0x4u);
    CHK_OWNED(g_gdv_audio_stream_base, 0x21d50u, 0x4u);
    CHK_OWNED(g_gdv_audio_enabled, 0x21dc8u, 0x1u);
    CHK_OWNED(g_gdv_audio_format, 0x21dcau, 0x1u);
    CHK_OWNED(g_gdv_decoder_active, 0x21ddcu, 0x1u);
    CHK_OWNED(g_gdv_end_of_stream, 0x21ddeu, 0x1u);
    CHK_OWNED(g_palette_dirty, 0x21de6u, 0x1u);
    CHK_OWNED(g_gdv_audio_end, 0x21df4u, 0x1u);
    CHK_OWNED(g_sector_count, 0x21df8u, 0x4u);
    CHK_OWNED(g_sector_section_offset, 0x21dfcu, 0x4u);
    CHK_OWNED(g_state_pool_a_count, 0x21e00u, 0x4u);
    CHK_OWNED(g_state_pool_a_records, 0x21e04u, 0x2b0u);
    CHK(g_sos_driver_active, 0x220b4u, 0x3cu);
    CHK_OWNED(g_sos_driver_type_ids, 0x220f0u, 0xeacu);
    CHK(g_sos_driver_vtable, 0x22f9cu, 0x1c8u);
    CHK_OWNED(g_sos_driver_descriptor, 0x23164u, 0x30u);
    CHK_OWNED(g_sos_drivers_installed, 0x23194u, 0x4u);
    CHK(g_extmidi_out_callback, 0x231b8u, 0x1ffcu);
    CHK(g_sos_midi_message, 0x251b4u, 0x18u);
    CHK_OWNED(g_sos_voice_alloc_mode, 0x251ccu, 0x4u);
    CHK(g_sos_timer_tick_flag, 0x251d0u, 0x2270u);
    CHK(g_sos_voice_table, 0x27440u, 0x584u);
    CHK(g_sos_timer_event_table, 0x279c4u, 0x1a0u);
    CHK(g_sos_timer_event_count, 0x27b64u, 0x1e0u);
    CHK(errno, 0x27d44u, 0x4u);
    CHK(_doserrno, 0x27d48u, 0x10428u);
#undef CHK
#undef CHK_OWNED
#undef CHK_OWNED_RELOC
    /* table-level: sorted, in-bounds, size<=OBJ3_SIZE window */
    for (unsigned i = 0; i < obj3_nsyms; i++) {
        const obj3_sym_t *s = &obj3_symtab[i];
        if (s->off + s->size > OBJ3_SIZE) sym_fail(s->name, "out of bounds");
        if (i && obj3_symtab[i-1].off >= s->off) sym_fail(s->name, "unsorted");
        if (s->off != s->va - 0x70000u) sym_fail(s->name, "va/off mismatch");
    }
    return nfail;
}

/* ---- reloc cross-reference (informational) ----
 * ALL 203 reloc slots stay on the runtime reloc pass (obj3_build):
 *   159 code->data slots (stay until fn symbols exist in the link)
 *   44 data->data slots, mapped below (slot -> target):
 *   slot 0x7079f (in g_snapshot_anim_frame+0x59               ) -> 0x7074c (g_snapshot_anim_frame+0x6)
 *   slot 0x707a3 (in g_snapshot_anim_frame+0x5d               ) -> 0x7074c (g_snapshot_anim_frame+0x6)
 *   slot 0x71241 (in g_inventory_tab_context_map+0x5          ) -> 0x80b74 (g_inventory_active_tab+0x4)
 *   slot 0x71245 (in g_inventory_tab_context_map+0x9          ) -> 0x80ba4 (g_inventory_active_tab+0x34)
 *   slot 0x718b8 (in g_choice_selected_index+0x548            ) -> 0x71420 (g_choice_selected_index+0xb0)
 *   slot 0x718bc (in g_choice_selected_index+0x54c            ) -> 0x71474 (g_choice_selected_index+0x104)
 *   slot 0x718c0 (in g_choice_selected_index+0x550            ) -> 0x714c8 (g_choice_selected_index+0x158)
 *   slot 0x718c4 (in g_choice_selected_index+0x554            ) -> 0x7166c (g_choice_selected_index+0x2fc)
 *   slot 0x718c8 (in g_choice_selected_index+0x558            ) -> 0x716c0 (g_choice_selected_index+0x350)
 *   slot 0x718cc (in g_choice_selected_index+0x55c            ) -> 0x71714 (g_choice_selected_index+0x3a4)
 *   slot 0x718d0 (in g_choice_selected_index+0x560            ) -> 0x71768 (g_choice_selected_index+0x3f8)
 *   slot 0x718d4 (in g_choice_selected_index+0x564            ) -> 0x71768 (g_choice_selected_index+0x3f8)
 *   slot 0x718d8 (in g_choice_selected_index+0x568            ) -> 0x71768 (g_choice_selected_index+0x3f8)
 *   slot 0x718dc (in g_choice_selected_index+0x56c            ) -> 0x71810 (g_choice_selected_index+0x4a0)
 *   slot 0x718e0 (in g_choice_selected_index+0x570            ) -> 0x715c4 (g_choice_selected_index+0x254)
 *   slot 0x718e4 (in g_choice_selected_index+0x574            ) -> 0x71618 (g_choice_selected_index+0x2a8)
 *   slot 0x718e8 (in g_choice_selected_index+0x578            ) -> 0x7151c (g_choice_selected_index+0x1ac)
 *   slot 0x718ec (in g_choice_selected_index+0x57c            ) -> 0x71570 (g_choice_selected_index+0x200)
 *   slot 0x718f0 (in g_choice_selected_index+0x580            ) -> 0x717bc (g_choice_selected_index+0x44c)
 *   slot 0x71f40 (in g_anim_step_fn_table+0x10                ) -> 0x8a140 (g_state_link_buf_ptr+0x4)
 *   slot 0x71f44 (in g_anim_step_fn_table+0x14                ) -> 0x8a1c4 (g_state_link_buf_ptr+0x88)
 *   slot 0x744d4 (in g_sos_timer_event_countdown+0x2d8        ) -> 0x760e0 (g_heap_free_list+0xad0)
 *   slot 0x744d8 (in g_sos_timer_event_countdown+0x2dc        ) -> 0x76106 (g_heap_free_list+0xaf6)
 *   slot 0x744dc (in g_sos_timer_event_countdown+0x2e0        ) -> 0x76125 (g_heap_free_list+0xb15)
 *   slot 0x744e0 (in g_sos_timer_event_countdown+0x2e4        ) -> 0x7613f (g_heap_free_list+0xb2f)
 *   slot 0x744e4 (in g_sos_timer_event_countdown+0x2e8        ) -> 0x76167 (g_heap_free_list+0xb57)
 *   slot 0x744e8 (in g_sos_timer_event_countdown+0x2ec        ) -> 0x76179 (g_heap_free_list+0xb69)
 *   slot 0x744ec (in g_sos_timer_event_countdown+0x2f0        ) -> 0x76193 (g_heap_free_list+0xb83)
 *   slot 0x744f0 (in g_sos_timer_event_countdown+0x2f4        ) -> 0x761a5 (g_heap_free_list+0xb95)
 *   slot 0x744f4 (in g_sos_timer_event_countdown+0x2f8        ) -> 0x761b6 (g_heap_free_list+0xba6)
 *   slot 0x744f8 (in g_sos_timer_event_countdown+0x2fc        ) -> 0x761df (g_heap_free_list+0xbcf)
 *   slot 0x744fc (in g_sos_timer_event_countdown+0x300        ) -> 0x7620c (g_heap_free_list+0xbfc)
 *   slot 0x74500 (in g_sos_timer_event_countdown+0x304        ) -> 0x7621b (g_heap_free_list+0xc0b)
 *   slot 0x74504 (in g_sos_timer_event_countdown+0x308        ) -> 0x76230 (g_heap_free_list+0xc20)
 *   slot 0x74508 (in g_sos_timer_event_countdown+0x30c        ) -> 0x76248 (g_heap_free_list+0xc38)
 *   slot 0x7450c (in g_sos_timer_event_countdown+0x310        ) -> 0x7625c (g_heap_free_list+0xc4c)
 *   slot 0x74510 (in g_sos_timer_event_countdown+0x314        ) -> 0x7626e (g_heap_free_list+0xc5e)
 *   slot 0x74514 (in g_sos_timer_event_countdown+0x318        ) -> 0x76289 (g_heap_free_list+0xc79)
 *   slot 0x74518 (in g_sos_timer_event_countdown+0x31c        ) -> 0x76298 (g_heap_free_list+0xc88)
 *   slot 0x7451c (in g_sos_timer_event_countdown+0x320        ) -> 0x762a6 (g_heap_free_list+0xc96)
 *   slot 0x74520 (in g_sos_timer_event_countdown+0x324        ) -> 0x762b4 (g_heap_free_list+0xca4)
 *   slot 0x7459a (in g_sos_timer_event_countdown+0x39e        ) -> 0x755aa (g_sos_timer_event_countdown+0x13ae)
 *   slot 0x75690 (in g_heap_free_list+0x80                    ) -> 0x75640 (g_heap_free_list+0x30)
 *   slot 0x758a1 (in g_heap_free_list+0x291                   ) -> 0x98158 (_doserrno+0x410)
 */
