/* GENERATED by recomp/datac/gen_obj3_c.py — do not edit by hand. */
#ifndef ROTH_OBJ3_DATA_H
#define ROTH_OBJ3_DATA_H
#include <stdint.h>

#define OBJ3_SIZE 229744u

/* obj3 (the engine's data object) expressed as C: raw pre-relocation bytes ... */
extern const unsigned char obj3_template[OBJ3_SIZE];

/* ... plus the relocation table that re-targets the baked-in pointers. */
typedef struct { uint32_t slot; uint8_t obj; uint32_t off; } obj3_reloc_t;
extern const obj3_reloc_t obj3_relocs[];
extern const unsigned obj3_nrelocs;

/* Reproduce the relocated image into `out` (OBJ3_SIZE bytes) for the given
 * per-object runtime bases: base[1]=obj1, base[2]=obj2, base[3]=obj3. */
void obj3_build(unsigned char *out, const uint32_t base[4]);

#endif /* ROTH_OBJ3_DATA_H */
