#!/usr/bin/env python3
"""gen_override_dispatch.py — emit the per-build override dispatch table + thunks.

Writes a GENERATED C translation unit (default roth_c/build/override_gen.c, gitignored) that the
standalone link compiles in. For every ELIGIBLE engine function (sdk/abi/override_targets.json) it
emits:

  * a per-function runtime slot        (struct roth_ovr_slot slot_<fn>)     — filled by the registry
  * the per-function DISPATCH THUNK     (roth_ovr_dispatch_<fn>)             — the boot patch's jmp
        target: builds the invocation-local chain from slot_<fn> and enters roth_next_<fn>
  * a row in the target table           (roth_ovr_targets[])                 — { id, name, &<fn>,
        &roth_ovr_dispatch_<fn>, &slot_<fn> }; the registry patches &<fn> (the pad entry) with a
        jmp to the dispatch thunk and records the original body (&<fn> + 5).

THE ADDRESS DESCRIPTOR IS SYMBOL REFERENCES, NOT BAKED ADDRESSES. `&<fn>` and `&dispatch` are
resolved by the LINKER, so there is no chicken-and-egg (no need to read a pre-linked binary), the
table survives `strip` (unlike a symtab self-inspection), and it is relocation-model-agnostic
(works under -no-pie today and a future PIE/Windows backend). The tradeoff: referencing `&<fn>`
keeps the ~80 otherwise-gc'd typed functions in the image (measured ~+2-3%), which is desirable —
it makes EVERY typed engine function overridable, not only those the standalone base path calls.

Names use a thunk-free vocabulary (roth_ovr_dispatch_<fn>): no call_orig /
lift_install / trampoline symbols are introduced.
"""
import json
import os
import sys

import sdk_common as C
import sdk_override_manifest as OVR

REPO = C.REPO
FUNCTIONS = os.path.join(REPO, "sdk", "schema", "functions.json")
OUT = os.path.join(REPO, "roth_c", "build", "override_gen.c")


def _pnames(params):
    return [p["name"] if p["name"] else f"a{i}" for i, p in enumerate(params)]


def render():
    by_id = {r["id"]: r for r in json.load(open(FUNCTIONS))["functions"]}
    rows = [by_id[t["id"]] for t in OVR.eligible_targets() if t["id"] in by_id]
    rows.sort(key=lambda r: r["id"])

    L = []
    w = L.append
    w("/* override_gen.c — GENERATED by tools/gen_override_dispatch.py — DO NOT EDIT.")
    w(" *")
    w(" * Per-build override dispatch table + thunks for the eligible engine functions")
    w(" * (sdk/abi/override_targets.json). Compiled into the roth game binary only; the registry")
    w(" * (src/platform/override_registry.c) patches each pad entry to its dispatch thunk at boot.")
    w(" * Addresses are SYMBOL REFERENCES resolved by the linker (strip-safe, no ELF self-inspection).")
    w(" */")
    w('#include "roth_sdk.h"            /* struct roth_chain, roth_next_<fn> (roth_sdk_overrides.h) */')
    w('#include "engine.h"              /* the real engine prototypes: &<fn> is the pad entry */')
    w('#include "override_registry.h"   /* struct roth_ovr_slot / roth_ovr_target */')
    w("")
    w(f"/* {len(rows)} eligible targets. */")
    w("")
    # per-function slots + dispatch thunks
    for r in rows:
        name = r["name"]
        ret = r["ret"].strip()
        params = r["params"]
        ptypes = [p["type"] for p in params]
        pnames = _pnames(params)
        star = "" if ret.endswith("*") else " "
        sigparams = []
        for t, n in zip(ptypes, pnames):
            sep = "" if t.endswith("*") else " "
            sigparams.append(f"{t}{sep}{n}")
        sig = ", ".join(sigparams) if sigparams else "void"
        # The entry is patched ONLY when the chain is non-empty (registry invariant n>=1), so the
        # thunk enters slot 0 directly (cursor pre-advanced to 1) — this drops the dead "cursor>=n =>
        # call base" branch that roth_next_<fn> carries for mid-chain use, keeping thunks compact.
        cb_call = ", ".join(["&c", f"slot_{name}.api"] + pnames)
        w(f"static struct roth_ovr_slot slot_{name};")
        w(f"{ret}{star}ROTH_CDECL roth_ovr_dispatch_{name}({sig}) {{")
        w(f"    struct roth_chain c = {{ slot_{name}.slots, slot_{name}.n, 1, "
          f"slot_{name}.body, slot_{name}.api }};")
        if ret == "void":
            w(f"    ((roth_override_{name}_fn)slot_{name}.slots[0])({cb_call});")
        else:
            w(f"    return ((roth_override_{name}_fn)slot_{name}.slots[0])({cb_call});")
        w("}")
    w("")
    # the target table
    w("const struct roth_ovr_target roth_ovr_targets[] = {")
    for r in rows:
        name = r["name"]
        w(f"    {{ 0x{r['id']:x}u, \"{name}\", (void *)&{name}, "
          f"(void *)&roth_ovr_dispatch_{name}, &slot_{name} }},")
    w("};")
    w(f"const int roth_ovr_target_count = {len(rows)};")
    return {OUT: "\n".join(L) + "\n"}, rows


def main():
    out = OUT
    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    if args:
        out = args[0]
    texts, rows = render()
    text = list(texts.values())[0]
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write(text)
    print(f"wrote {out}  ({len(rows)} eligible dispatch thunks)")


if __name__ == "__main__":
    main()
