#!/usr/bin/env python3
"""sdk_gen.py — generate the public SDK artifacts from the checked-in schemas.

Inputs  (sources of truth, checked in):
  sdk/schema/functions.json    typed engine signatures; exposed set drives the wrappers
  sdk/schema/sdk_api.json      hand-curated non-engine surface (version, game_ram, contexts)

Outputs (generated, checked in; CI regenerates-and-diffs against them):
  sdk/include/roth_sdk.h       the public header (types, ID enum, API tables, wrappers,
                               game_ram accessors, context-tagged callbacks)
  sdk/abi/descriptor.json      machine ABI descriptor (i386 struct field offsets/sizes,
                               table slot order, signature ids) that CI diffs vs releases
  sdk/generated/host_adapters.c a STANDALONE-compilable adapter table that is ALSO a
                               compile-time proof that the generated wrapper types match
                               engine.h exactly (the moddable binary links it as the host
                               API table).

i386 ABI model: every API-table field is a function pointer (4 bytes, 4-align); the
top-level struct leads with abi_major(u16)/abi_minor(u16)/struct_size(u32).
Offsets are computed analytically here and VALIDATED empirically by tools/sdk_check.py
(which compiles+runs an offsetof probe under -m32).
"""
import json
import os

import sdk_common as C
import sdk_override_manifest as OVR

SDK = os.path.join(C.REPO, "sdk")
FUNCTIONS = os.path.join(SDK, "schema", "functions.json")
SDK_API = os.path.join(SDK, "schema", "sdk_api.json")
HDR = os.path.join(SDK, "include", "roth_sdk.h")
OVR_HDR = os.path.join(SDK, "include", "roth_sdk_overrides.h")
DESC = os.path.join(SDK, "abi", "descriptor.json")
ADAPTERS = os.path.join(SDK, "generated", "host_adapters.c")

PTR = 4  # i386 function-pointer size/alignment

ENGINE_STRUCT = "roth_engine_api_v1"
GR_STRUCT = "roth_game_ram_api_v1"
API_STRUCT = "roth_api_v1"
HOST_TABLE = "roth_host_api_v1"
REGISTRAR_STRUCT = "roth_registrar_v1"
CHAIN_STRUCT = "roth_chain"


def _param_types(params):
    return [p["type"] for p in params]


def _fnptr(ret, params, field, cdecl="ROTH_CDECL"):
    """Render a function-pointer struct field: `ret (CDECL *field)(types);`"""
    types = ", ".join(_param_types(params)) or "void"
    ret = ret.strip()
    star = "" if ret.endswith("*") else " "
    return f"{ret}{star}({cdecl} *{field})({types});"


def _pnames(params):
    """Parameter names for a generated function body; synthesize a<i> for unnamed engine.h params."""
    return [p["name"] if p["name"] else f"a{i}" for i, p in enumerate(params)]


def _fnptr_cast(ret, types):
    """A bare function-pointer TYPE for a cast: `ret (ROTH_CDECL *)(types)`."""
    ret = ret.strip()
    star = "" if ret.endswith("*") else " "
    return f"{ret}{star}(ROTH_CDECL *)({', '.join(types) or 'void'})"


# ---------------------------------------------------- roth_sdk_overrides.h ----
def gen_overrides_header(sigs):
    """The GENERATED per-eligible-function override machinery:
    one invocation-local chain struct, and per function a typed callback typedef + a
    roth_next_<fn>() thunk that advances the chain (and at the end enters the recorded
    original body). Kept OUT of roth_sdk.h's core (included at its end) to keep that file
    readable — this file is ~1000 functions long. Casts go object-ptr(void*) -> fn-ptr so
    they trip only -Wpedantic (not enabled), never -Wcast-function-type."""
    L = []
    w = L.append
    w("/* roth_sdk_overrides.h — GENERATED per-function override callback machinery.")
    w(" *")
    w(" * GENERATED by tools/sdk_gen.py from sdk/abi/override_targets.json (the eligible set) +")
    w(" * sdk/schema/functions.json (the typed signatures) — DO NOT EDIT BY HAND.")
    w(" * Included at the END of roth_sdk.h; do not include directly. Regenerate: make -C sdk gen.")
    w(" *")
    w(" * For each ELIGIBLE (overrideable) engine function this provides:")
    w(" *   typedef roth_override_<fn>_fn  — your override callback's type:")
    w(" *       RET (chain*, const roth_api_v1* api, <original args...>)")
    w(" *   roth_next_<fn>(chain, <args...>) — call the next link, or the recorded original body.")
    w(" * Register one with: roth_override(reg, ROTH_FN_<fn>, my_cb, priority) in on_register_overrides.")
    w(" */")
    w("#ifndef ROTH_SDK_OVERRIDES_H")
    w("#define ROTH_SDK_OVERRIDES_H")
    w("/* Requires roth_sdk.h (ROTH_CDECL, struct roth_api_v1) already included. */")
    w("")
    w("/* Invocation-local chain context (a stack object built by the host dispatch thunk; no TLS).")
    w("   slots = the immutable, priority-sorted callbacks (as void*); base = recorded original body")
    w("   (winner entry + 5). Higher priority runs first (outer). */")
    w(f"struct {CHAIN_STRUCT} {{")
    w("    const void *const *slots;           /* [n] typed roth_override_<fn>_fn, stored as void* */")
    w("    int n;")
    w("    int cursor;")
    w("    void *base;                         /* recorded original body = winner entry + 5 */")
    w(f"    const struct {API_STRUCT} *api;")
    w("};")
    w("")
    # `roth_ctx` names the chain-context param — chosen so it never collides with an engine
    # parameter name (the engine set has a param literally named `chain`; `roth_` is the SDK namespace).
    ctx = "roth_ctx"
    for r in sigs:
        name = r["name"]
        ret = r["ret"].strip()
        params = r["params"]
        ptypes = _param_types(params)
        pnames = _pnames(params)
        # public callback typedef: (chain*, api*, original args...)
        cb_params = [f"struct {CHAIN_STRUCT} *chain", f"const struct {API_STRUCT} *api"]
        cb_params += list(ptypes)
        star = "" if ret.endswith("*") else " "
        w(f"typedef {ret}{star}(ROTH_CDECL *roth_override_{name}_fn)({', '.join(cb_params)});")
        # next-thunk signature: (roth_ctx*, original named args...)
        nx_params = [f"struct {CHAIN_STRUCT} *{ctx}"]
        for t, n in zip(ptypes, pnames):
            sep = "" if t.endswith("*") else " "
            nx_params.append(f"{t}{sep}{n}")
        base_cast = _fnptr_cast(ret, ptypes)
        call_args = ", ".join(pnames)
        cb_call_args = ", ".join([ctx, f"{ctx}->api"] + pnames)
        w(f"static inline {ret}{star}roth_next_{name}({', '.join(nx_params)}) {{")
        if ret == "void":
            w(f"    if ({ctx}->cursor >= {ctx}->n) {{ (({base_cast}){ctx}->base)({call_args}); return; }}")
            w(f"    ((roth_override_{name}_fn){ctx}->slots[{ctx}->cursor++])({cb_call_args});")
        else:
            w(f"    if ({ctx}->cursor >= {ctx}->n) return (({base_cast}){ctx}->base)({call_args});")
            w(f"    return ((roth_override_{name}_fn){ctx}->slots[{ctx}->cursor++])({cb_call_args});")
        w("}")
    w("")
    w("#endif /* ROTH_SDK_OVERRIDES_H */")
    return "\n".join(L) + "\n"


PLUGIN_STRUCT = "roth_plugin_info_v1"


def _scalar_sz_align(t):
    """(size, align) for a plugin-info field type on i386. Non-scalars are pointers."""
    if t == "uint16_t":
        return 2, 2
    if t == "uint32_t":
        return 4, 4
    return PTR, PTR  # const char * / a callback typedef / any pointer


def _plugin_field_type(f):
    """The declared C type of a plugin-info field ('type' scalar/pointer, or a callback typedef)."""
    return f.get("type") or f["typedef"]


def _plugin_layout(fields):
    """Compute i386 offsets/sizes for the plugin-info struct (natural alignment, struct align 4).
    Returns (rows, struct_size); rows carry {name, type, offset, size, kind}."""
    rows = []
    off = 0
    struct_align = PTR
    for f in fields:
        t = _plugin_field_type(f)
        sz, al = _scalar_sz_align(f.get("type", ""))
        if f.get("typedef"):
            sz, al = PTR, PTR
        off = (off + al - 1) & ~(al - 1)
        kind = ("uint16" if f.get("type") == "uint16_t" else
                "uint32" if f.get("type") == "uint32_t" else "fnptr")
        rows.append({"name": f["name"], "type": t, "offset": off, "size": sz, "kind": kind})
        off += sz
    size = (off + struct_align - 1) & ~(struct_align - 1)
    return rows, size


def _gen_overrides_api(w, api):
    """Emit the hand-curated registration surface: the roth_register_override_fn typedef, the
    roth_registrar_v1 struct the host hands on_register_overrides, and the roth_override() macro."""
    ov = api.get("overrides")
    if not ov:
        return
    sig = ov["register_signature"]
    types = ", ".join(p["type"] for p in sig["params"])
    ret = sig["ret"].strip()
    star = "" if ret.endswith("*") else " "
    w("/* ---- runtime override registration --------------------------------------- */")
    w(f"typedef {ret}{star}(ROTH_CDECL *{ov['register_typedef']})({types});")
    w("/* The host hands this to on_register_overrides; call roth_override(reg, ROTH_FN_<fn>, cb, prio). */")
    w(f"struct {ov['registrar_struct']} {{")
    for f in ov["registrar_fields"]:
        if f.get("typedef"):
            w(f"    {f['typedef']} {f['name']};" + (f"  /* {f.get('desc','')} */" if f.get("desc") else ""))
        else:
            t = f["type"]
            s = "" if t.endswith("*") else " "
            w(f"    {t}{s}{f['name']};" + (f"  /* {f.get('desc','')} */" if f.get("desc") else ""))
    w("};")
    w("/* Convenience: record an override for ROTH_FN_<fn> (cast your typed callback to void*). */")
    w(f"#define roth_override(reg, fn_id, cb, prio) "
      f"((reg)->override((reg), (uint32_t)(fn_id), (void *)(cb), (int)(prio)))")
    w("")


def _gen_plugin_header(w, api):
    pl = api.get("plugin")
    if not pl:
        return
    au = pl["api_use"]
    w("/* ---- declared API use (diagnostics ONLY) --------------------------------- */")
    w("/* A self-declared compatibility hint set. The loader validates it as a subset check,")
    w("   NEVER as a sandbox: a native plugin is arbitrary in-process code (see README). */")
    w(f"enum {au['enum_name']} {{")
    for e in au["values"]:
        w(f"    {e['name']} = {e['value']},  /* {e['desc']} */")
    w("};")
    w("")
    w("/* ---- the single versioned plugin export + its info struct ---------------- */")
    w("/* A plugin ships mods/<name>/plugin.so exporting exactly ONE function:")
    w(f"       ROTH_PLUGIN_EXPORT const struct {PLUGIN_STRUCT} *{pl['query_export']}(void);")
    w("   returning a pointer to a static, immutable info struct. abi_major/abi_minor/")
    w("   struct_size lead it; the loader accepts the plugin iff")
    w("   abi_major == host AND abi_minor <= host. A NULL callback = not interested. */")
    w(f"struct {PLUGIN_STRUCT} {{")
    for f in pl["info_fields"]:
        t = _plugin_field_type(f)
        if f.get("typedef"):
            w(f"    {t} {f['name']};")
        else:
            star = "" if t.endswith("*") else " "
            desc = f.get("desc", "")
            w(f"    {t}{star}{f['name']};" + (f"  /* {desc} */" if desc else ""))
    w("};")
    w("")
    w(f"/* The plugin's one export (host resolves it by dlsym). */")
    w(f"ROTH_PLUGIN_EXPORT const struct {PLUGIN_STRUCT} *{pl['query_export']}(void);")
    w("")


def load():
    fdoc = json.load(open(FUNCTIONS))
    exposed = [r for r in fdoc["functions"] if r["exposed"]]
    # THE EXPOSED-ORDER LAW: engine-call-table slot order = exposure order (exposed_slot, assigned
    # from the ordered STARTER_SET in tools/sdk_extract_signatures.py), append-only forever — NOT
    # id-sort (which would shift existing slot offsets on every new low-id exposure).
    exposed.sort(key=lambda r: r["exposed_slot"])
    if [r["exposed_slot"] for r in exposed] != list(range(len(exposed))):
        raise SystemExit("exposed_slot values are not contiguous 0..n-1 — regenerate functions.json")
    api = json.load(open(SDK_API))
    return exposed, api


def load_override_sigs():
    """The eligible override targets joined to their full typed signature (from functions.json),
    id-sorted. Each row is the functions.json dict; this drives roth_sdk_overrides.h generation."""
    fdoc = json.load(open(FUNCTIONS))
    by_id = {r["id"]: r for r in fdoc["functions"]}
    rows = [by_id[t["id"]] for t in OVR.eligible_targets() if t["id"] in by_id]
    rows.sort(key=lambda r: r["id"])
    return rows


# --------------------------------------------------------------- header -------
def gen_header(exposed, sigs, api):
    v = api["version"]
    ctx = api["contexts"]
    gr = api["game_ram"]
    cbs = api["callbacks"]
    L = []
    w = L.append
    w("/* roth_sdk.h — the ROTH.C modding SDK public header.")
    w(" *")
    w(" * GENERATED by tools/sdk_gen.py from the sdk/schema JSON files — DO NOT EDIT BY HAND.")
    w(" * Regenerate: python3 tools/sdk_gen.py --write  (or: make -C sdk gen)")
    w(" *")
    w(" * The engine surface is ordinary i386 C ABI (the original Watcom register")
    w(" * convention survives only as parameter ORDER). Plugins call engine functions")
    w(" * ONLY through the host-provided API table below — never by linking engine")
    w(" * symbols directly. Function identity is a permanent numeric ID == the canonical")
    w(" * 1996 VA (see sdk/schema/function_ids.json).")
    w(" */")
    w("#ifndef ROTH_SDK_H")
    w("#define ROTH_SDK_H")
    w("")
    w("#include <stdint.h>")
    w("#include <stddef.h>")
    w("")
    w("#ifdef __cplusplus")
    w('extern "C" {')
    w("#endif")
    w("")
    w("/* ---- versions ------------------------------------------------------------ */")
    w(f"#define ROTH_SDK_MAJOR {v['sdk_major']}")
    w(f"#define ROTH_SDK_MINOR {v['sdk_minor']}")
    w(f"#define ROTH_ABI_MAJOR {v['abi_major']}")
    w(f"#define ROTH_ABI_MINOR {v['abi_minor']}")
    w("/* Load rule: plugin loads iff abi_major == host AND abi_minor <= host. */")
    w("")
    w("/* ---- calling convention / visibility ------------------------------------- */")
    w("/* The engine surface is i386 cdecl (the default); ROTH_CDECL is a no-op there and")
    w("   a placeholder for a future Windows/stdcall split. */")
    w("#if defined(__i386__) && (defined(__GNUC__) || defined(__clang__))")
    w("#  define ROTH_CDECL __attribute__((__cdecl__))")
    w("#else")
    w("#  define ROTH_CDECL")
    w("#endif")
    w("#if defined(__GNUC__) || defined(__clang__)")
    w('#  define ROTH_SDK_EXPORT __attribute__((visibility("default")))')
    w("#else")
    w("#  define ROTH_SDK_EXPORT")
    w("#endif")
    w("/* Plugins mark their single versioned query export with ROTH_PLUGIN_EXPORT so the host")
    w("   dlsym resolves it regardless of -fvisibility=hidden. */")
    w("#if defined(__GNUC__) || defined(__clang__)")
    w('#  define ROTH_PLUGIN_EXPORT __attribute__((visibility("default")))')
    w("#else")
    w("#  define ROTH_PLUGIN_EXPORT")
    w("#endif")
    w("")
    w("/* ---- execution contexts — SDK law ---------------------------------------- */")
    w(f"typedef enum {ctx['enum_name']} {{")
    for e in ctx["values"]:
        w(f"    {e['name']} = {e['value']},  /* {e['desc']} */")
    w(f"}} {ctx['enum_name']};")
    w("")
    w("/* ---- permanent function IDs (id == canonical 1996 VA) --------------------- */")
    w("/* Every OVERRIDABLE (eligible) engine function, so ROTH_FN_<fn> names any override target for")
    w("   roth_override(); the exposed engine-call table below is the subset callable through the api. */")
    w("enum roth_fn_id {")
    for r in sigs:
        w(f"    ROTH_FN_{r['name']} = 0x{r['id']:x},")
    w("};")
    w("")
    w("/* ---- engine-call table: one typed slot per exposed function --------------- */")
    w("/* SLOT ORDER = EXPOSURE ORDER (a frozen ABI, append-only forever): new functions")
    w("   are only ever appended at the end, so existing slot offsets never move. */")
    w(f"struct {ENGINE_STRUCT} {{")
    for r in exposed:
        w("    " + _fnptr(r["ret"], r["params"], r["name"]) + f"  /* id 0x{r['id']:x} */")
    w("};")
    w("")
    w("/* ---- game_ram accessors: bounded little-endian --------------------------- */")
    w("/* Offsets are canonical VAs = the frozen 1996 layout. Out-of-range reads -> 0,")
    w("   out-of-range writes dropped, block ops return -1. Pool-lifetime rule: never")
    w("   cache a pool-derived pointer across an engine call or tick (see README). */")
    w(f"struct {GR_STRUCT} {{")
    for a in gr["accessors"]:
        w("    " + _fnptr(a["ret"], a["params"], a["name"]) + f"  /* {a['desc']} */")
    w("};")
    w("")
    w("/* ---- the host-provided API table (abi header first) ---------------------- */")
    w(f"struct {API_STRUCT} {{")
    w("    uint16_t abi_major;")
    w("    uint16_t abi_minor;")
    w("    uint32_t struct_size;               /* sizeof(struct " + API_STRUCT + ") */")
    w(f"    const struct {ENGINE_STRUCT}  *engine;")
    w(f"    const struct {GR_STRUCT} *game_ram;")
    for f in api.get("host_api", {}).get("fields", []):   # host services appended after game_ram (10)
        w("    " + _fnptr(f["ret"], f["params"], f["name"]) + (f"  /* {f['desc']} */" if f.get("desc") else ""))
    w("};")
    w("")
    w("/* ---- context-tagged lifecycle callbacks ---------------------------------- */")
    w(f"struct {API_STRUCT};")
    w(f"struct {REGISTRAR_STRUCT};   /* fwd: the override registrar handed to on_register_overrides */")
    mp = api.get("mouse_poll")   # public struct referenced by an on_mouse_poll param — emit before the typedefs
    if mp:
        w(f"/* {mp['struct_name']}: the SDK-neutral int33 mouse-poll view handed to on_mouse_poll (see sdk_api.json). */")
        w(f"struct {mp['struct_name']} {{")
        for f in mp["fields"]:
            t = f["type"]
            s = "" if t.endswith("*") else " "
            w(f"    {t}{s}{f['name']};" + (f"  /* {f['desc']} */" if f.get("desc") else ""))
        w("};")
    for t in cbs["typedefs"]:
        ret = t.get("ret", "void").strip()
        star = "" if ret.endswith("*") else " "
        plist = f"const struct {API_STRUCT} *api"
        for p in t.get("params", []):
            sep = "" if p["type"].endswith("*") else " "
            plist += f", {p['type']}{sep}{p['name']}"
        w(f"typedef {ret}{star}({'ROTH_CDECL'} *{t['name']})({plist});"
          f"  /* {t['context']}: {t['desc']} */")
    w("")
    _gen_overrides_api(w, api)
    w('#include "roth_sdk_overrides.h"   /* GENERATED per-function typedefs + roth_next_<fn> thunks */')
    w("")
    _gen_plugin_header(w, api)
    w("/* ---- convenience call macros (call an exposed engine fn through the table) - */")
    for r in exposed:
        w(f"#define ROTH_CALL_{r['name']}(api, ...) ((api)->engine->{r['name']}(__VA_ARGS__))")
    w("")
    w("#ifdef __cplusplus")
    w("}")
    w("#endif")
    w("#endif /* ROTH_SDK_H */")
    return "\n".join(L) + "\n"


# ------------------------------------------------------------ descriptor ------
def gen_descriptor(exposed, api):
    v = api["version"]
    gr = api["game_ram"]
    ctx = api["contexts"]

    engine_fields = []
    off = 0
    for i, r in enumerate(exposed):
        engine_fields.append({
            "slot": i, "name": r["name"], "id": r["id"], "va": r["va"],
            "signature_id": r["id"], "offset": off, "size": PTR,
            "kind": "fnptr", "ret": r["ret"], "params": _param_types(r["params"]),
        })
        off += PTR
    engine_size = off

    gr_fields = []
    off = 0
    for i, a in enumerate(gr["accessors"]):
        gr_fields.append({
            "slot": i, "name": a["name"], "offset": off, "size": PTR,
            "kind": "fnptr", "ret": a["ret"], "params": _param_types(a["params"]),
        })
        off += PTR
    gr_size = off

    api_fields = [
        {"name": "abi_major", "offset": 0, "size": 2, "kind": "uint16"},
        {"name": "abi_minor", "offset": 2, "size": 2, "kind": "uint16"},
        {"name": "struct_size", "offset": 4, "size": 4, "kind": "uint32"},
        {"name": "engine", "offset": 8, "size": PTR, "kind": "ptr",
         "points_to": ENGINE_STRUCT},
        {"name": "game_ram", "offset": 12, "size": PTR, "kind": "ptr",
         "points_to": GR_STRUCT},
    ]
    api_size = 16
    for f in api.get("host_api", {}).get("fields", []):   # host services appended after game_ram
        api_fields.append({"name": f["name"], "offset": api_size, "size": PTR, "kind": "fnptr"})
        api_size += PTR

    structs = {
        API_STRUCT: {"size": api_size, "fields": api_fields},
        ENGINE_STRUCT: {"size": engine_size, "fields": engine_fields},
        GR_STRUCT: {"size": gr_size, "fields": gr_fields},
    }
    # the SDK-neutral int33 mouse-poll view (on_mouse_poll param) — tracked so abi-probe verifies it.
    mp = api.get("mouse_poll")
    if mp:
        mp_rows, mp_size = _plugin_layout(mp["fields"])
        structs[mp["struct_name"]] = {"size": mp_size, "fields": mp_rows}
    # plugin-side info struct — tracked so abi-probe verifies its i386 layout.
    pl = api.get("plugin")
    if pl:
        pl_rows, pl_size = _plugin_layout(pl["info_fields"])
        structs[PLUGIN_STRUCT] = {"size": pl_size, "fields": pl_rows}
    # override registrar — the host->plugin registration boundary.
    ov = api.get("overrides")
    if ov:
        structs[REGISTRAR_STRUCT] = {"size": 8, "fields": [
            {"name": "struct_size", "offset": 0, "size": 4, "kind": "uint32"},
            {"name": "override", "offset": 4, "size": PTR, "kind": "fnptr"},
        ]}
        # invocation-local chain context — host-built, consumed by the plugin's roth_next_<fn>.
        structs[CHAIN_STRUCT] = {"size": 20, "fields": [
            {"name": "slots", "offset": 0, "size": PTR, "kind": "ptr"},
            {"name": "n", "offset": 4, "size": 4, "kind": "int"},
            {"name": "cursor", "offset": 8, "size": 4, "kind": "int"},
            {"name": "base", "offset": 12, "size": PTR, "kind": "ptr"},
            {"name": "api", "offset": 16, "size": PTR, "kind": "ptr", "points_to": API_STRUCT},
        ]}

    desc = {
        "schema": "roth-sdk/abi_descriptor/v1",
        "note": ("Machine ABI descriptor: i386 struct field offsets/sizes, API-table slot "
                 "order, and signature ids. tools/sdk_check.py diffs this against "
                 "sdk/abi/released/ and enforces the bump policy (identical=ok, "
                 "append-only=minor, otherwise=major)."),
        "sdk_major": v["sdk_major"], "sdk_minor": v["sdk_minor"],
        "abi_major": v["abi_major"], "abi_minor": v["abi_minor"],
        "arch": "i386", "ptr_size": PTR,
        "structs": structs,
        "engine_table": engine_fields,
        "game_ram_table": gr_fields,
        "contexts": ctx["values"],
    }
    return json.dumps(desc, indent=1) + "\n"


# ------------------------------------------------------- host adapters --------
def gen_adapters(exposed, api):
    gr = api["game_ram"]
    L = []
    w = L.append
    w("/* host_adapters.c — GENERATED host-adapter table (tools/sdk_gen.py).")
    w(" *")
    w(" * Provides the host-side API table plugins call through: the engine-call table")
    w(" * (each slot bound to the real engine.h function) plus the bounded little-endian")
    w(" * game_ram accessors. Binding each engine slot to its engine.h symbol is also a")
    w(" * COMPILE-TIME ABI PROOF — if a generated wrapper type disagreed with engine.h,")
    w(" * this file would not compile.")
    w(" *")
    w(" * Standalone build check: gcc -m32 -std=c11 -Wall -Wextra -c \\")
    w(" *   -Isdk/include -Iroth_c/src/engine sdk/generated/host_adapters.c")
    w(" */")
    w("#include <stdint.h>")
    w("#include <string.h>")
    w('#include "roth_sdk.h"')
    w('#include "engine.h"   /* the real engine prototypes: slot = &fn must type-check */')
    w("")
    w("/* game_ram base+size are provided by the host at link time. */")
    w("extern uint8_t  *roth_game_ram_base;")
    w("extern uint32_t  roth_game_ram_size;")
    w("")
    w("/* ---- bounded little-endian game_ram accessors ---------------------------- */")
    w("static uint8_t gr_u8(uint32_t off) {")
    w("    return (off < roth_game_ram_size) ? roth_game_ram_base[off] : (uint8_t)0;")
    w("}")
    w("static uint16_t gr_u16(uint32_t off) {")
    w("    if ((uint64_t)off + 2 > roth_game_ram_size) return 0;")
    w("    const uint8_t *p = roth_game_ram_base + off;")
    w("    return (uint16_t)((uint16_t)p[0] | ((uint16_t)p[1] << 8));")
    w("}")
    w("static uint32_t gr_u32(uint32_t off) {")
    w("    if ((uint64_t)off + 4 > roth_game_ram_size) return 0;")
    w("    const uint8_t *p = roth_game_ram_base + off;")
    w("    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) |")
    w("           ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);")
    w("}")
    w("static void gr_set_u8(uint32_t off, uint8_t v) {")
    w("    if (off < roth_game_ram_size) roth_game_ram_base[off] = v;")
    w("}")
    w("static void gr_set_u16(uint32_t off, uint16_t v) {")
    w("    if ((uint64_t)off + 2 > roth_game_ram_size) return;")
    w("    uint8_t *p = roth_game_ram_base + off;")
    w("    p[0] = (uint8_t)v; p[1] = (uint8_t)(v >> 8);")
    w("}")
    w("static void gr_set_u32(uint32_t off, uint32_t v) {")
    w("    if ((uint64_t)off + 4 > roth_game_ram_size) return;")
    w("    uint8_t *p = roth_game_ram_base + off;")
    w("    p[0] = (uint8_t)v; p[1] = (uint8_t)(v >> 8);")
    w("    p[2] = (uint8_t)(v >> 16); p[3] = (uint8_t)(v >> 24);")
    w("}")
    w("static int gr_read_block(uint32_t off, void *dst, uint32_t n) {")
    w("    if ((uint64_t)off + n > roth_game_ram_size) return -1;")
    w("    memcpy(dst, roth_game_ram_base + off, n); return 0;")
    w("}")
    w("static int gr_write_block(uint32_t off, const void *src, uint32_t n) {")
    w("    if ((uint64_t)off + n > roth_game_ram_size) return -1;")
    w("    memcpy(roth_game_ram_base + off, src, n); return 0;")
    w("}")
    w("static uint32_t gr_size(void) { return roth_game_ram_size; }")
    w("/* resolve a canonical VA to its host pointer (base+off); NULL out of range. VA->host-ptr op. */")
    w("static void *gr_to_ptr(uint32_t off) {")
    w("    return (off < roth_game_ram_size) ? (void *)(roth_game_ram_base + off) : (void *)0;")
    w("}")
    w("")
    order = [a["name"] for a in gr["accessors"]]
    fnmap = {"u8": "gr_u8", "u16": "gr_u16", "u32": "gr_u32", "set_u8": "gr_set_u8",
             "set_u16": "gr_set_u16", "set_u32": "gr_set_u32", "read_block": "gr_read_block",
             "write_block": "gr_write_block", "size": "gr_size", "to_ptr": "gr_to_ptr"}
    w(f"static const struct {GR_STRUCT} GR = {{")
    for nm in order:
        w(f"    .{nm} = {fnmap[nm]},")
    w("};")
    w("")
    w("/* ---- engine-call table: slot = the real engine.h symbol (the ABI proof) --- */")
    w(f"static const struct {ENGINE_STRUCT} ENG = {{")
    for r in exposed:
        w(f"    .{r['name']} = {r['name']},")
    w("};")
    w("")
    host_fields = api.get("host_api", {}).get("fields", [])
    if host_fields:
        w("/* host services on the top-level table: provided by the host loader (extern here — the")
        w(" * standalone -c ABI proof leaves them unresolved; the standalone game link binds plugin_loader.o). */")
        for f in host_fields:
            ret = f["ret"].strip()
            star = "" if ret.endswith("*") else " "
            types = ", ".join(p["type"] for p in f.get("params", [])) or "void"
            w(f"extern {ret}{star}{f['host_symbol']}({types});")
        w("")
    w(f"ROTH_SDK_EXPORT const struct {API_STRUCT} {HOST_TABLE} = {{")
    w("    .abi_major = ROTH_ABI_MAJOR,")
    w("    .abi_minor = ROTH_ABI_MINOR,")
    w(f"    .struct_size = (uint32_t)sizeof(struct {API_STRUCT}),")
    w("    .engine = &ENG,")
    w("    .game_ram = &GR,")
    for f in host_fields:
        w(f"    .{f['name']} = {f['host_symbol']},")
    w("};")
    return "\n".join(L) + "\n"


def render():
    """Return {path: text} for the generated public artifacts (single source used by
    both the writer and the CI drift check)."""
    exposed, api = load()
    sigs = load_override_sigs()
    return {
        HDR: gen_header(exposed, sigs, api),
        OVR_HDR: gen_overrides_header(sigs),
        DESC: gen_descriptor(exposed, api),
        ADAPTERS: gen_adapters(exposed, api),
    }, exposed


def main():
    import sys
    texts, exposed = render()
    sigs = load_override_sigs()
    if "--write" in sys.argv or "--seed" in sys.argv:
        for path, text in texts.items():
            open(path, "w").write(text)
            print(f"wrote {path}")
        print(f"  exposed engine slots: {len(exposed)}; override typedefs: {len(sigs)}")
    else:
        print(f"[dry-run] {len(exposed)} exposed slots, {len(sigs)} override typedefs "
              f"— pass --write to emit")


if __name__ == "__main__":
    main()
